services:
  local-mondeydb:
    extends:
      file: docker-compose.yml
      service: mondeydb
    ports:
      - "5432:5432"
  local-usersdb:
    extends:
      file: docker-compose.yml
      service: usersdb
    ports:
      - "5433:5432"
