services:
  backend:
    image: ghcr.io/ssciwr/mondey_backend:${MONDEY_DOCKER_IMAGE_TAG:-latest}
    build: ./mondey_backend
    volumes:
      - ${STATIC_FILES_PATH:-./static}:/app/static
      - ${DATABASE_PATH:-./db}:/app/db
      - ${PRIVATE_FILES_PATH:-./private}:/app/private
    environment:
      - SECRET=${SECRET:-}
      - STATIC_FILES_PATH=/app/static
      - PRIVATE_FILES_PATH=/app/private
      - DATABASE_PATH=/app/db
      - ENABLE_CORS=${ENABLE_CORS:-false}
      - HOST=${HOST:-backend}
      - PORT=${PORT:-80}
      - RELOAD=${RELOAD:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - STATS_CRONTAB=${STATS_CRONTAB:-0 3 * * mon}
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 25
  frontend:
    image: ghcr.io/ssciwr/mondey_frontend:${MONDEY_DOCKER_IMAGE_TAG:-latest}
    build:
      context: ./frontend
      args:
        - MONDEY_API_URL=/api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${MONDEY_SSL_CERT:-./cert.pem}:/mondey_ssl_cert.pem
      - ${MONDEY_SSL_KEY:-./key.pem}:/mondey_ssl_key.pem
      # to allow certbot to renew SSL certificates:
      - /var/www/certbot:/var/www/certbot:ro
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 25
  email:
    image: "boky/postfix"
    environment:
      - ALLOW_EMPTY_SENDER_DOMAINS="true"
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 3
