services:
  backend:
    image: ghcr.io/ssciwr/mondey_backend:${MONDEY_DOCKER_IMAGE_TAG:-latest}
    build: ./mondey_backend
    volumes:
      - ${STATIC_FILES_PATH:-./static}:/app/static
      - ${DATABASE_PATH:-./db}:/app/db
      - ${PRIVATE_FILES_PATH:-./private}:/app/private
    environment:
      - SECRET=${SECRET:-}
      - DATABASE_PATH=/app/db
      - STATIC_FILES_PATH=/app/static
      - PRIVATE_FILES_PATH=/app/private
      - HOST=${HOST:-backend}
      - PORT=${PORT:-80}
      - SMTP_HOST=${SMTP_HOST:-email:587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - RELOAD=false
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - COOKIE_SECURE=${COOKIE_SECURE:-true}
      - STATS_CRONTAB=${STATS_CRONTAB:-0 3 * * mon}
      - DEEPL_API_KEY=${DEEPL_API_KEY:-}
      - MONDEY_HOST=${MONDEY_HOST:-mondey.lkeegan.dev}
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 25
  frontend:
    image: ghcr.io/ssciwr/mondey_frontend:${MONDEY_DOCKER_IMAGE_TAG:-latest}
    build:
      context: ./frontend
      args:
        - MONDEY_API_URL=/api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${MONDEY_SSL_CERT:-./cert.pem}:/mondey_ssl_cert.pem
      - ${MONDEY_SSL_KEY:-./key.pem}:/mondey_ssl_key.pem
      # to allow certbot to renew SSL certificates:
      - /var/www/certbot:/var/www/certbot:ro
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 25
  email:
    image: "boky/postfix"
    hostname: mail.mondey.lkeegan.dev
    restart: always
    environment:
      - RELAYHOST=${RELAYHOST:-}
      - POSTFIX_myhostname=mail.mondey.lkeegan.dev
      - POSTFIX_mydomain=mondey.lkeegan.dev
      - ALLOWED_SENDER_DOMAINS=mondey.lkeegan.dev
      - DKIM_AUTOGENERATE=true
    volumes:
      - ./opendkim-keys:/etc/opendkim/keys
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 3
