services:
  backend:
    image: ghcr.io/ssciwr/mondey_backend:${MONDEY_DOCKER_IMAGE_TAG:-latest}
    restart: always
    build: ./mondey_backend
    volumes:
      - ${STATIC_FILES_PATH:-./static}:/app/static
      - ${PRIVATE_FILES_PATH:-./private}:/app/private
    environment:
      - SECRET=${SECRET:-}
      - DATABASE_HOST_MONDEYDB=${DATABASE_HOST_MONDEYDB:-mondeydb}
      - DATABASE_HOST_USERSDB=${DATABASE_HOST_USERSDB:-usersdb}
      - DATABASE_USER=${DATABASE_USER:-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - STATIC_FILES_PATH=/app/static
      - PRIVATE_FILES_PATH=/app/private
      - HOST=${HOST:-backend}
      - PORT=${PORT:-80}
      - SMTP_HOST=${SMTP_HOST:-email:587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - RELOAD=false
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - COOKIE_SECURE=${COOKIE_SECURE:-true}
      - STATS_CRONTAB=${STATS_CRONTAB:-0 3 * * mon}
      - DEEPL_API_KEY=${DEEPL_API_KEY:-}
      - MONDEY_HOST=${MONDEY_HOST:-mondey.de}
    depends_on:
      - mondeydb
      - usersdb
      - email
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 25
  frontend:
    image: ghcr.io/ssciwr/mondey_frontend:${MONDEY_DOCKER_IMAGE_TAG:-latest}
    restart: always
    build:
      context: ./frontend
      args:
        - MONDEY_API_URL=/api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${MONDEY_SSL_CERT:-./cert.pem}:/mondey_ssl_cert.pem
      - ${MONDEY_SSL_KEY:-./key.pem}:/mondey_ssl_key.pem
      # to allow certbot to renew SSL certificates:
      - /var/www/certbot:/var/www/certbot:ro
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 25
  mondeydb:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    volumes:
      - ${POSTGRES_DATA_PATH_MONDEY:-./db/mondey}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-}
      - POSTGRES_DB=mondey
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 5
  usersdb:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    volumes:
      - ${POSTGRES_DATA_PATH_USER:-./db/users}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-}
      - POSTGRES_DB=users
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 5
  email:
    image: "boky/postfix"
    hostname: mail.mondey.de
    restart: always
    environment:
      - RELAYHOST=${RELAYHOST:-}
      - POSTFIX_myhostname=mail.mondey.de
      - POSTFIX_mydomain=mondey.de
      - ALLOWED_SENDER_DOMAINS=mondey.de
      - DKIM_AUTOGENERATE=true
    volumes:
      - ./opendkim-keys:/etc/opendkim/keys
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 3
  mondeydb-backup:
    image: prodrigestivill/postgres-backup-local:17-alpine
    restart: always
    volumes:
        - ${POSTGRES_DATA_PATH_MONDEY_BACKUPS:-./db_backups/mondey}:/backups
    links:
        - mondeydb
    depends_on:
        - mondeydb
    environment:
        - POSTGRES_HOST=mondeydb
        - POSTGRES_DB=mondey
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-}
        - POSTGRES_EXTRA_OPTS=--compress=zstd --clean
        - SCHEDULE=@daily
        - BACKUP_ON_START=TRUE
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - HEALTHCHECK_PORT=8080
  usersdb-backup:
    image: prodrigestivill/postgres-backup-local:17-alpine
    restart: always
    volumes:
        - ${POSTGRES_DATA_PATH_USER_BACKUPS:-./db_backups/users}:/backups
    links:
        - usersdb
    depends_on:
        - usersdb
    environment:
        - POSTGRES_HOST=usersdb
        - POSTGRES_DB=users
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-}
        - POSTGRES_EXTRA_OPTS=--compress=zstd --clean
        - SCHEDULE=@daily
        - BACKUP_ON_START=TRUE
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - HEALTHCHECK_PORT=8080
  watchtower:
    image: containrrr/watchtower
    restart: always
    command:
      - --cleanup=true
      - --remove-volumes=true
      - --schedule=0 0 1 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
