"""Add CalendarEvent table

Revision ID: 05e995d24ed9
Revises: d686ee296232
Create Date: 2025-09-26 11:52:03.915107

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05e995d24ed9"
down_revision: str | Sequence[str] | None = "d686ee296232"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendarevent")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendarevent",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("external_link", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("event_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("calendarevent_pkey")),
    )
    # ### end Alembic commands ###
