// This file is auto-generated by @hey-api/openapi-ts

export type AdminSettingsPublic = {
    hide_milestone_feedback: boolean;
    hide_milestone_group_feedback: boolean;
    hide_all_feedback: boolean;
};

export type AdminSettingsUpdate = {
    hide_milestone_feedback?: boolean | null;
    hide_milestone_group_feedback?: boolean | null;
    hide_all_feedback?: boolean | null;
};

export type BodyAuthCookieLoginAuthLoginPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type BodyCreateDocumentAdminDocumentsPost = {
    title: string;
    description: string;
    file: string;
};

export type BodyImportCsvDataAdminResearchImportCsvPost = {
    /**
     * Additional data CSV file
     */
    additional_data_file: string;
    /**
     * Labels CSV file
     */
    labels_file?: string;
};

export type BodyResetForgotPasswordAuthForgotPasswordPost = {
    email: string;
};

export type BodyResetResetPasswordAuthResetPasswordPost = {
    token: string;
    password: string;
};

export type BodySubmitMilestoneImageSubmittedMilestoneImagesMilestoneIdPost = {
    file: string;
};

export type BodyUploadChildImageUsersChildrenImagesChildIdPut = {
    file: string;
};

export type BodyUploadMilestoneGroupImageAdminMilestoneGroupImagesMilestoneGroupIdPut = {
    file: string;
};

export type BodyUploadMilestoneImageAdminMilestoneImagesMilestoneIdPost = {
    file: string;
};

export type BodyVerifyRequestTokenAuthRequestVerifyTokenPost = {
    email: string;
};

export type BodyVerifyVerifyAuthVerifyPost = {
    token: string;
};

export type CalendarEventCreate = {
    title?: string;
    description?: string;
    external_link?: string;
    event_date: string;
};

export type CalendarEventRead = {
    title?: string;
    description?: string;
    external_link?: string;
    event_date: string;
    id: number;
};

export type CalendarEventUpdate = {
    title?: string | null;
    description?: string | null;
    external_link?: string | null;
    event_date?: string | null;
};

export type ChildAnswerPublic = {
    answer: string;
    additional_answer: string | null;
    question_id: number;
};

export type ChildCreate = {
    name?: string;
    birth_year: number;
    birth_month: number;
    color?: string | null;
};

export type ChildPublic = {
    name?: string;
    birth_year: number;
    birth_month: number;
    color?: string | null;
    id: number;
    has_image: boolean;
};

export type ChildQuestionAdmin = {
    order?: number;
    component?: string;
    type?: string;
    options?: string;
    additional_option?: string;
    required?: boolean;
    name?: string;
    visibility?: boolean;
    id: number;
    text?: {
        [key: string]: ChildQuestionText;
    };
};

export type ChildQuestionPublic = {
    id: number;
    component?: string;
    type?: string;
    text?: {
        [key: string]: QuestionTextPublic;
    };
    additional_option?: string;
    required?: boolean;
    name?: string;
};

export type ChildQuestionText = {
    question?: string;
    options_json?: string;
    options?: string;
    child_question_id?: number | null;
    lang_id?: string | null;
};

export type ChildSummaryPublic = {
    name?: string;
    birth_year: number;
    birth_month: number;
    color?: string | null;
    id: number;
    has_image: boolean;
    active_answer_session: boolean;
    session_progress: number;
    session_remaining_seconds: number;
};

export type DeleteResponse = {
    ok: boolean;
    dry_run: boolean;
    children: {
        [key: string]: number;
    };
    /**
     * Error message when present
     */
    error?: string | null;
};

export type DocumentAdmin = {
    title?: string;
    description?: string;
    filename?: string;
    id: number;
    created_at: string;
    uploaded_by_user_id: number;
};

export type DocumentCreate = {
    title?: string;
    description?: string;
    filename?: string;
};

export type DocumentPublic = {
    title?: string;
    description?: string;
    filename?: string;
    id: number;
    created_at: string;
    uploaded_by_user_id: number;
};

export type ErrorModel = {
    detail: string | {
        [key: string]: string;
    };
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemOrder = {
    id: number;
    order: number;
};

export type Language = {
    id: string;
};

export type MilestoneAdmin = {
    id: number;
    group_id: number;
    order: number;
    expected_age_months: number;
    relevant_age_min: number;
    relevant_age_max: number;
    text: {
        [key: string]: MilestoneText;
    };
    images: Array<MilestoneImage>;
    name: string;
};

export type MilestoneAgeScore = {
    milestone_id?: number | null;
    age: number;
    c0: number;
    c1: number;
    c2: number;
    c3: number;
};

export type MilestoneAgeScoreCollectionPublic = {
    milestone_id: number;
    expected_age: number;
    relevant_age_min: number;
    relevant_age_max: number;
    scores: Array<MilestoneAgeScore>;
};

export type MilestoneAnswerAnalysis = {
    milestone_id: number;
    answer: number;
    avg_answer: number;
    stddev_answer: number;
};

export type MilestoneAnswerPublic = {
    milestone_id: number;
    answer: number;
};

export type MilestoneAnswerResponse = {
    answer: MilestoneAnswerPublic;
    session_completed: boolean;
};

export type MilestoneAnswerSession = {
    id?: number | null;
    child_id: number;
    user_id: number;
    created_at: string;
    expired: boolean;
    completed: boolean;
    included_in_statistics: boolean;
    suspicious_state?: string;
};

export type MilestoneAnswerSessionAnalysis = {
    child_age: number;
    rms: number;
    answers: Array<MilestoneAnswerAnalysis>;
};

export type MilestoneAnswerSessionPublic = {
    id: number;
    child_id: number;
    created_at: string;
    answers: {
        [key: string]: MilestoneAnswerPublic;
    };
};

export type MilestoneGroupAdmin = {
    id: number;
    order: number;
    text: {
        [key: string]: MilestoneGroupText;
    };
    milestones: Array<MilestoneAdmin>;
};

export type MilestoneGroupPublic = {
    id: number;
    text: {
        [key: string]: MilestoneGroupTextPublic;
    };
    milestones: Array<MilestonePublic>;
};

export type MilestoneGroupText = {
    title?: string;
    desc?: string;
    group_id?: number | null;
    lang_id?: string | null;
};

export type MilestoneGroupTextPublic = {
    title?: string;
    desc?: string;
};

export type MilestoneImage = {
    id?: number | null;
    milestone_id?: number | null;
};

export type MilestoneImagePublic = {
    id: number;
};

export type MilestonePublic = {
    id: number;
    text: {
        [key: string]: MilestoneTextPublic;
    };
    images: Array<MilestoneImagePublic>;
    name: string;
};

export type MilestoneText = {
    title?: string;
    desc?: string;
    obs?: string;
    help?: string;
    importance?: string;
    milestone_id?: number | null;
    lang_id?: string | null;
};

export type MilestoneTextPublic = {
    title?: string;
    desc?: string;
    obs?: string;
    help?: string;
    importance?: string;
};

export type QuestionTextPublic = {
    question?: string;
    options_json?: string;
    options?: string;
};

export type ResearchGroup = {
    id: number;
};

export type SubmittedMilestoneImagePublic = {
    id: number;
    milestone_id: number;
    user_id: number;
};

export type UserAnswerPublic = {
    answer: string;
    additional_answer: string | null;
    question_id: number;
};

export type UserCreate = {
    email: string;
    password: string;
    is_active?: boolean | null;
    is_superuser?: boolean | null;
    is_verified?: boolean | null;
    is_researcher?: boolean | null;
    full_data_access?: boolean | null;
    research_group_id?: number | null;
};

export type UserQuestionAdmin = {
    order?: number;
    component?: string;
    type?: string;
    options?: string;
    additional_option?: string;
    required?: boolean;
    name?: string;
    visibility?: boolean;
    id: number;
    text?: {
        [key: string]: UserQuestionText;
    };
};

export type UserQuestionPublic = {
    id: number;
    component?: string;
    type?: string;
    text?: {
        [key: string]: QuestionTextPublic;
    };
    additional_option?: string;
    required?: boolean;
    name?: string;
};

export type UserQuestionText = {
    question?: string;
    options_json?: string;
    options?: string;
    user_question_id?: number | null;
    lang_id?: string | null;
};

export type UserRead = {
    id: number;
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_verified?: boolean;
    is_researcher: boolean;
    full_data_access: boolean;
    research_group_id: number;
};

export type UserUpdate = {
    password?: string | null;
    email?: string | null;
    is_active?: boolean | null;
    is_superuser?: boolean | null;
    is_verified?: boolean | null;
    is_researcher?: boolean | null;
    full_data_access?: boolean | null;
    research_group_id?: number | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetEventsEventsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/events/';
};

export type GetEventsEventsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<CalendarEventRead>;
};

export type GetEventsEventsGetResponse = GetEventsEventsGetResponses[keyof GetEventsEventsGetResponses];

export type GetPublicDocumentsDocumentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/documents/';
};

export type GetPublicDocumentsDocumentsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<DocumentPublic>;
};

export type GetPublicDocumentsDocumentsGetResponse = GetPublicDocumentsDocumentsGetResponses[keyof GetPublicDocumentsDocumentsGetResponses];

export type GetLanguagesLanguagesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/languages/';
};

export type GetLanguagesLanguagesGetResponses = {
    /**
     * Successful Response
     */
    200: Array<string>;
};

export type GetLanguagesLanguagesGetResponse = GetLanguagesLanguagesGetResponses[keyof GetLanguagesLanguagesGetResponses];

export type GetMilestonesMilestonesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/milestones/';
};

export type GetMilestonesMilestonesGetResponses = {
    /**
     * Successful Response
     */
    200: Array<MilestonePublic>;
};

export type GetMilestonesMilestonesGetResponse = GetMilestonesMilestonesGetResponses[keyof GetMilestonesMilestonesGetResponses];

export type GetMilestoneMilestonesMilestoneIdGetData = {
    body?: never;
    path: {
        milestone_id: number;
    };
    query?: never;
    url: '/milestones/{milestone_id}';
};

export type GetMilestoneMilestonesMilestoneIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMilestoneMilestonesMilestoneIdGetError = GetMilestoneMilestonesMilestoneIdGetErrors[keyof GetMilestoneMilestonesMilestoneIdGetErrors];

export type GetMilestoneMilestonesMilestoneIdGetResponses = {
    /**
     * Successful Response
     */
    200: MilestonePublic;
};

export type GetMilestoneMilestonesMilestoneIdGetResponse = GetMilestoneMilestonesMilestoneIdGetResponses[keyof GetMilestoneMilestonesMilestoneIdGetResponses];

export type GetMilestoneGroupsMilestoneGroupsChildIdGetData = {
    body?: never;
    path: {
        child_id: number;
    };
    query?: never;
    url: '/milestone-groups/{child_id}';
};

export type GetMilestoneGroupsMilestoneGroupsChildIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMilestoneGroupsMilestoneGroupsChildIdGetError = GetMilestoneGroupsMilestoneGroupsChildIdGetErrors[keyof GetMilestoneGroupsMilestoneGroupsChildIdGetErrors];

export type GetMilestoneGroupsMilestoneGroupsChildIdGetResponses = {
    /**
     * Successful Response
     */
    200: Array<MilestoneGroupPublic>;
};

export type GetMilestoneGroupsMilestoneGroupsChildIdGetResponse = GetMilestoneGroupsMilestoneGroupsChildIdGetResponses[keyof GetMilestoneGroupsMilestoneGroupsChildIdGetResponses];

export type SubmitMilestoneImageSubmittedMilestoneImagesMilestoneIdPostData = {
    body: BodySubmitMilestoneImageSubmittedMilestoneImagesMilestoneIdPost;
    path: {
        milestone_id: number;
    };
    query?: never;
    url: '/submitted-milestone-images/{milestone_id}';
};

export type SubmitMilestoneImageSubmittedMilestoneImagesMilestoneIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitMilestoneImageSubmittedMilestoneImagesMilestoneIdPostError = SubmitMilestoneImageSubmittedMilestoneImagesMilestoneIdPostErrors[keyof SubmitMilestoneImageSubmittedMilestoneImagesMilestoneIdPostErrors];

export type SubmitMilestoneImageSubmittedMilestoneImagesMilestoneIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserQuestionsUserQuestionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user-questions/';
};

export type GetUserQuestionsUserQuestionsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<UserQuestionPublic>;
};

export type GetUserQuestionsUserQuestionsGetResponse = GetUserQuestionsUserQuestionsGetResponses[keyof GetUserQuestionsUserQuestionsGetResponses];

export type GetChildQuestionsChildQuestionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/child-questions/';
};

export type GetChildQuestionsChildQuestionsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<ChildQuestionPublic>;
};

export type GetChildQuestionsChildQuestionsGetResponse = GetChildQuestionsChildQuestionsGetResponses[keyof GetChildQuestionsChildQuestionsGetResponses];

export type CreateEventAdminCalendareventsPostData = {
    body: CalendarEventCreate;
    path?: never;
    query?: never;
    url: '/admin/calendarevents/';
};

export type CreateEventAdminCalendareventsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEventAdminCalendareventsPostError = CreateEventAdminCalendareventsPostErrors[keyof CreateEventAdminCalendareventsPostErrors];

export type CreateEventAdminCalendareventsPostResponses = {
    /**
     * Successful Response
     */
    200: CalendarEventRead;
};

export type CreateEventAdminCalendareventsPostResponse = CreateEventAdminCalendareventsPostResponses[keyof CreateEventAdminCalendareventsPostResponses];

export type DeleteEventAdminCalendareventsEventIdDeleteData = {
    body?: never;
    path: {
        event_id: number;
    };
    query?: never;
    url: '/admin/calendarevents/{event_id}';
};

export type DeleteEventAdminCalendareventsEventIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEventAdminCalendareventsEventIdDeleteError = DeleteEventAdminCalendareventsEventIdDeleteErrors[keyof DeleteEventAdminCalendareventsEventIdDeleteErrors];

export type DeleteEventAdminCalendareventsEventIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateEventAdminCalendareventsEventIdPutData = {
    body: CalendarEventUpdate;
    path: {
        event_id: number;
    };
    query?: never;
    url: '/admin/calendarevents/{event_id}';
};

export type UpdateEventAdminCalendareventsEventIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEventAdminCalendareventsEventIdPutError = UpdateEventAdminCalendareventsEventIdPutErrors[keyof UpdateEventAdminCalendareventsEventIdPutErrors];

export type UpdateEventAdminCalendareventsEventIdPutResponses = {
    /**
     * Successful Response
     */
    200: CalendarEventRead;
};

export type UpdateEventAdminCalendareventsEventIdPutResponse = UpdateEventAdminCalendareventsEventIdPutResponses[keyof UpdateEventAdminCalendareventsEventIdPutResponses];

export type GetDocumentsAdminDocumentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/documents/';
};

export type GetDocumentsAdminDocumentsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<DocumentAdmin>;
};

export type GetDocumentsAdminDocumentsGetResponse = GetDocumentsAdminDocumentsGetResponses[keyof GetDocumentsAdminDocumentsGetResponses];

export type CreateDocumentAdminDocumentsPostData = {
    body: BodyCreateDocumentAdminDocumentsPost;
    path?: never;
    query?: never;
    url: '/admin/documents/';
};

export type CreateDocumentAdminDocumentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDocumentAdminDocumentsPostError = CreateDocumentAdminDocumentsPostErrors[keyof CreateDocumentAdminDocumentsPostErrors];

export type CreateDocumentAdminDocumentsPostResponses = {
    /**
     * Successful Response
     */
    200: DocumentAdmin;
};

export type CreateDocumentAdminDocumentsPostResponse = CreateDocumentAdminDocumentsPostResponses[keyof CreateDocumentAdminDocumentsPostResponses];

export type DeleteDocumentAdminDocumentsDocumentIdDeleteData = {
    body?: never;
    path: {
        document_id: number;
    };
    query?: never;
    url: '/admin/documents/{document_id}';
};

export type DeleteDocumentAdminDocumentsDocumentIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDocumentAdminDocumentsDocumentIdDeleteError = DeleteDocumentAdminDocumentsDocumentIdDeleteErrors[keyof DeleteDocumentAdminDocumentsDocumentIdDeleteErrors];

export type DeleteDocumentAdminDocumentsDocumentIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateDocumentAdminDocumentsDocumentIdPutData = {
    body: DocumentCreate;
    path: {
        document_id: number;
    };
    query?: never;
    url: '/admin/documents/{document_id}';
};

export type UpdateDocumentAdminDocumentsDocumentIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDocumentAdminDocumentsDocumentIdPutError = UpdateDocumentAdminDocumentsDocumentIdPutErrors[keyof UpdateDocumentAdminDocumentsDocumentIdPutErrors];

export type UpdateDocumentAdminDocumentsDocumentIdPutResponses = {
    /**
     * Successful Response
     */
    200: DocumentAdmin;
};

export type UpdateDocumentAdminDocumentsDocumentIdPutResponse = UpdateDocumentAdminDocumentsDocumentIdPutResponses[keyof UpdateDocumentAdminDocumentsDocumentIdPutResponses];

export type CreateLanguageAdminLanguagesPostData = {
    body: Language;
    path?: never;
    query?: never;
    url: '/admin/languages/';
};

export type CreateLanguageAdminLanguagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLanguageAdminLanguagesPostError = CreateLanguageAdminLanguagesPostErrors[keyof CreateLanguageAdminLanguagesPostErrors];

export type CreateLanguageAdminLanguagesPostResponses = {
    /**
     * Successful Response
     */
    200: Language;
};

export type CreateLanguageAdminLanguagesPostResponse = CreateLanguageAdminLanguagesPostResponses[keyof CreateLanguageAdminLanguagesPostResponses];

export type DeleteLanguageAdminLanguagesLanguageIdDeleteData = {
    body?: never;
    path: {
        language_id: string;
    };
    query?: never;
    url: '/admin/languages/{language_id}';
};

export type DeleteLanguageAdminLanguagesLanguageIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLanguageAdminLanguagesLanguageIdDeleteError = DeleteLanguageAdminLanguagesLanguageIdDeleteErrors[keyof DeleteLanguageAdminLanguagesLanguageIdDeleteErrors];

export type DeleteLanguageAdminLanguagesLanguageIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateI18nAdminI18nLanguageIdPutData = {
    body: {
        [key: string]: {
            [key: string]: string;
        };
    };
    path: {
        language_id: string;
    };
    query?: never;
    url: '/admin/i18n/{language_id}';
};

export type UpdateI18nAdminI18nLanguageIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateI18nAdminI18nLanguageIdPutError = UpdateI18nAdminI18nLanguageIdPutErrors[keyof UpdateI18nAdminI18nLanguageIdPutErrors];

export type UpdateI18nAdminI18nLanguageIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TranslateAdminTranslatePostData = {
    body?: never;
    path?: never;
    query: {
        text: string;
        locale: string;
        source_lang?: string;
    };
    url: '/admin/translate/';
};

export type TranslateAdminTranslatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranslateAdminTranslatePostError = TranslateAdminTranslatePostErrors[keyof TranslateAdminTranslatePostErrors];

export type TranslateAdminTranslatePostResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type TranslateAdminTranslatePostResponse = TranslateAdminTranslatePostResponses[keyof TranslateAdminTranslatePostResponses];

export type GetMilestoneGroupsAdminAdminMilestoneGroupsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/milestone-groups/';
};

export type GetMilestoneGroupsAdminAdminMilestoneGroupsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<MilestoneGroupAdmin>;
};

export type GetMilestoneGroupsAdminAdminMilestoneGroupsGetResponse = GetMilestoneGroupsAdminAdminMilestoneGroupsGetResponses[keyof GetMilestoneGroupsAdminAdminMilestoneGroupsGetResponses];

export type CreateMilestoneGroupAdminAdminMilestoneGroupsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/milestone-groups/';
};

export type CreateMilestoneGroupAdminAdminMilestoneGroupsPostResponses = {
    /**
     * Successful Response
     */
    200: MilestoneGroupAdmin;
};

export type CreateMilestoneGroupAdminAdminMilestoneGroupsPostResponse = CreateMilestoneGroupAdminAdminMilestoneGroupsPostResponses[keyof CreateMilestoneGroupAdminAdminMilestoneGroupsPostResponses];

export type UpdateMilestoneGroupAdminAdminMilestoneGroupsPutData = {
    body: MilestoneGroupAdmin;
    path?: never;
    query?: never;
    url: '/admin/milestone-groups';
};

export type UpdateMilestoneGroupAdminAdminMilestoneGroupsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMilestoneGroupAdminAdminMilestoneGroupsPutError = UpdateMilestoneGroupAdminAdminMilestoneGroupsPutErrors[keyof UpdateMilestoneGroupAdminAdminMilestoneGroupsPutErrors];

export type UpdateMilestoneGroupAdminAdminMilestoneGroupsPutResponses = {
    /**
     * Successful Response
     */
    200: MilestoneGroupAdmin;
};

export type UpdateMilestoneGroupAdminAdminMilestoneGroupsPutResponse = UpdateMilestoneGroupAdminAdminMilestoneGroupsPutResponses[keyof UpdateMilestoneGroupAdminAdminMilestoneGroupsPutResponses];

export type DeleteMilestoneGroupAdminAdminMilestoneGroupsMilestoneGroupIdDeleteData = {
    body?: never;
    path: {
        milestone_group_id: number;
    };
    query?: {
        /**
         * When true, shows what would be deleted without actually deleting
         */
        dry_run?: boolean;
    };
    url: '/admin/milestone-groups/{milestone_group_id}';
};

export type DeleteMilestoneGroupAdminAdminMilestoneGroupsMilestoneGroupIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMilestoneGroupAdminAdminMilestoneGroupsMilestoneGroupIdDeleteError = DeleteMilestoneGroupAdminAdminMilestoneGroupsMilestoneGroupIdDeleteErrors[keyof DeleteMilestoneGroupAdminAdminMilestoneGroupsMilestoneGroupIdDeleteErrors];

export type DeleteMilestoneGroupAdminAdminMilestoneGroupsMilestoneGroupIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteResponse;
};

export type DeleteMilestoneGroupAdminAdminMilestoneGroupsMilestoneGroupIdDeleteResponse = DeleteMilestoneGroupAdminAdminMilestoneGroupsMilestoneGroupIdDeleteResponses[keyof DeleteMilestoneGroupAdminAdminMilestoneGroupsMilestoneGroupIdDeleteResponses];

export type OrderMilestoneGroupsAdminAdminMilestoneGroupsOrderPostData = {
    body: Array<ItemOrder>;
    path?: never;
    query?: never;
    url: '/admin/milestone-groups/order/';
};

export type OrderMilestoneGroupsAdminAdminMilestoneGroupsOrderPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrderMilestoneGroupsAdminAdminMilestoneGroupsOrderPostError = OrderMilestoneGroupsAdminAdminMilestoneGroupsOrderPostErrors[keyof OrderMilestoneGroupsAdminAdminMilestoneGroupsOrderPostErrors];

export type OrderMilestoneGroupsAdminAdminMilestoneGroupsOrderPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadMilestoneGroupImageAdminMilestoneGroupImagesMilestoneGroupIdPutData = {
    body: BodyUploadMilestoneGroupImageAdminMilestoneGroupImagesMilestoneGroupIdPut;
    path: {
        milestone_group_id: number;
    };
    query?: never;
    url: '/admin/milestone-group-images/{milestone_group_id}';
};

export type UploadMilestoneGroupImageAdminMilestoneGroupImagesMilestoneGroupIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadMilestoneGroupImageAdminMilestoneGroupImagesMilestoneGroupIdPutError = UploadMilestoneGroupImageAdminMilestoneGroupImagesMilestoneGroupIdPutErrors[keyof UploadMilestoneGroupImageAdminMilestoneGroupImagesMilestoneGroupIdPutErrors];

export type UploadMilestoneGroupImageAdminMilestoneGroupImagesMilestoneGroupIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateMilestoneAdminMilestonesMilestoneGroupIdPostData = {
    body?: never;
    path: {
        milestone_group_id: number;
    };
    query?: never;
    url: '/admin/milestones/{milestone_group_id}';
};

export type CreateMilestoneAdminMilestonesMilestoneGroupIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMilestoneAdminMilestonesMilestoneGroupIdPostError = CreateMilestoneAdminMilestonesMilestoneGroupIdPostErrors[keyof CreateMilestoneAdminMilestonesMilestoneGroupIdPostErrors];

export type CreateMilestoneAdminMilestonesMilestoneGroupIdPostResponses = {
    /**
     * Successful Response
     */
    200: MilestoneAdmin;
};

export type CreateMilestoneAdminMilestonesMilestoneGroupIdPostResponse = CreateMilestoneAdminMilestonesMilestoneGroupIdPostResponses[keyof CreateMilestoneAdminMilestonesMilestoneGroupIdPostResponses];

export type UpdateMilestoneAdminMilestonesPutData = {
    body: MilestoneAdmin;
    path?: never;
    query?: never;
    url: '/admin/milestones/';
};

export type UpdateMilestoneAdminMilestonesPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMilestoneAdminMilestonesPutError = UpdateMilestoneAdminMilestonesPutErrors[keyof UpdateMilestoneAdminMilestonesPutErrors];

export type UpdateMilestoneAdminMilestonesPutResponses = {
    /**
     * Successful Response
     */
    200: MilestoneAdmin;
};

export type UpdateMilestoneAdminMilestonesPutResponse = UpdateMilestoneAdminMilestonesPutResponses[keyof UpdateMilestoneAdminMilestonesPutResponses];

export type DeleteMilestoneAdminMilestonesMilestoneIdDeleteData = {
    body?: never;
    path: {
        milestone_id: number;
    };
    query?: {
        /**
         * When true, shows what would be deleted without actually deleting
         */
        dry_run?: boolean;
    };
    url: '/admin/milestones/{milestone_id}';
};

export type DeleteMilestoneAdminMilestonesMilestoneIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMilestoneAdminMilestonesMilestoneIdDeleteError = DeleteMilestoneAdminMilestonesMilestoneIdDeleteErrors[keyof DeleteMilestoneAdminMilestonesMilestoneIdDeleteErrors];

export type DeleteMilestoneAdminMilestonesMilestoneIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteResponse;
};

export type DeleteMilestoneAdminMilestonesMilestoneIdDeleteResponse = DeleteMilestoneAdminMilestonesMilestoneIdDeleteResponses[keyof DeleteMilestoneAdminMilestonesMilestoneIdDeleteResponses];

export type OrderMilestonesAdminAdminMilestonesOrderPostData = {
    body: Array<ItemOrder>;
    path?: never;
    query?: never;
    url: '/admin/milestones/order/';
};

export type OrderMilestonesAdminAdminMilestonesOrderPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrderMilestonesAdminAdminMilestonesOrderPostError = OrderMilestonesAdminAdminMilestonesOrderPostErrors[keyof OrderMilestonesAdminAdminMilestonesOrderPostErrors];

export type OrderMilestonesAdminAdminMilestonesOrderPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadMilestoneImageAdminMilestoneImagesMilestoneIdPostData = {
    body: BodyUploadMilestoneImageAdminMilestoneImagesMilestoneIdPost;
    path: {
        milestone_id: number;
    };
    query?: never;
    url: '/admin/milestone-images/{milestone_id}';
};

export type UploadMilestoneImageAdminMilestoneImagesMilestoneIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadMilestoneImageAdminMilestoneImagesMilestoneIdPostError = UploadMilestoneImageAdminMilestoneImagesMilestoneIdPostErrors[keyof UploadMilestoneImageAdminMilestoneImagesMilestoneIdPostErrors];

export type UploadMilestoneImageAdminMilestoneImagesMilestoneIdPostResponses = {
    /**
     * Successful Response
     */
    200: MilestoneImage;
};

export type UploadMilestoneImageAdminMilestoneImagesMilestoneIdPostResponse = UploadMilestoneImageAdminMilestoneImagesMilestoneIdPostResponses[keyof UploadMilestoneImageAdminMilestoneImagesMilestoneIdPostResponses];

export type DeleteMilestoneImageAdminMilestoneImagesMilestoneImageIdDeleteData = {
    body?: never;
    path: {
        milestone_image_id: number;
    };
    query?: never;
    url: '/admin/milestone-images/{milestone_image_id}';
};

export type DeleteMilestoneImageAdminMilestoneImagesMilestoneImageIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMilestoneImageAdminMilestoneImagesMilestoneImageIdDeleteError = DeleteMilestoneImageAdminMilestoneImagesMilestoneImageIdDeleteErrors[keyof DeleteMilestoneImageAdminMilestoneImagesMilestoneImageIdDeleteErrors];

export type DeleteMilestoneImageAdminMilestoneImagesMilestoneImageIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSubmittedMilestoneImagesAdminSubmittedMilestoneImagesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/submitted-milestone-images/';
};

export type GetSubmittedMilestoneImagesAdminSubmittedMilestoneImagesGetResponses = {
    /**
     * Successful Response
     */
    200: Array<SubmittedMilestoneImagePublic>;
};

export type GetSubmittedMilestoneImagesAdminSubmittedMilestoneImagesGetResponse = GetSubmittedMilestoneImagesAdminSubmittedMilestoneImagesGetResponses[keyof GetSubmittedMilestoneImagesAdminSubmittedMilestoneImagesGetResponses];

export type ApproveSubmittedMilestoneImageAdminSubmittedMilestoneImagesApproveSubmittedMilestoneImageIdPostData = {
    body?: never;
    path: {
        submitted_milestone_image_id: number;
    };
    query?: never;
    url: '/admin/submitted-milestone-images/approve/{submitted_milestone_image_id}';
};

export type ApproveSubmittedMilestoneImageAdminSubmittedMilestoneImagesApproveSubmittedMilestoneImageIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveSubmittedMilestoneImageAdminSubmittedMilestoneImagesApproveSubmittedMilestoneImageIdPostError = ApproveSubmittedMilestoneImageAdminSubmittedMilestoneImagesApproveSubmittedMilestoneImageIdPostErrors[keyof ApproveSubmittedMilestoneImageAdminSubmittedMilestoneImagesApproveSubmittedMilestoneImageIdPostErrors];

export type ApproveSubmittedMilestoneImageAdminSubmittedMilestoneImagesApproveSubmittedMilestoneImageIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteSubmittedMilestoneImageAdminSubmittedMilestoneImagesSubmittedMilestoneImageIdDeleteData = {
    body?: never;
    path: {
        submitted_milestone_image_id: number;
    };
    query?: never;
    url: '/admin/submitted-milestone-images/{submitted_milestone_image_id}';
};

export type DeleteSubmittedMilestoneImageAdminSubmittedMilestoneImagesSubmittedMilestoneImageIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSubmittedMilestoneImageAdminSubmittedMilestoneImagesSubmittedMilestoneImageIdDeleteError = DeleteSubmittedMilestoneImageAdminSubmittedMilestoneImagesSubmittedMilestoneImageIdDeleteErrors[keyof DeleteSubmittedMilestoneImageAdminSubmittedMilestoneImagesSubmittedMilestoneImageIdDeleteErrors];

export type DeleteSubmittedMilestoneImageAdminSubmittedMilestoneImagesSubmittedMilestoneImageIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMilestoneAgeScoresAdminMilestoneAgeScoresMilestoneIdGetData = {
    body?: never;
    path: {
        milestone_id: number;
    };
    query?: never;
    url: '/admin/milestone-age-scores/{milestone_id}';
};

export type GetMilestoneAgeScoresAdminMilestoneAgeScoresMilestoneIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMilestoneAgeScoresAdminMilestoneAgeScoresMilestoneIdGetError = GetMilestoneAgeScoresAdminMilestoneAgeScoresMilestoneIdGetErrors[keyof GetMilestoneAgeScoresAdminMilestoneAgeScoresMilestoneIdGetErrors];

export type GetMilestoneAgeScoresAdminMilestoneAgeScoresMilestoneIdGetResponses = {
    /**
     * Successful Response
     */
    200: MilestoneAgeScoreCollectionPublic;
};

export type GetMilestoneAgeScoresAdminMilestoneAgeScoresMilestoneIdGetResponse = GetMilestoneAgeScoresAdminMilestoneAgeScoresMilestoneIdGetResponses[keyof GetMilestoneAgeScoresAdminMilestoneAgeScoresMilestoneIdGetResponses];

export type AdminUpdateStatsAdminUpdateStatsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/update-stats/';
};

export type AdminUpdateStatsAdminUpdateStatsPostResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type AdminUpdateStatsAdminUpdateStatsPostResponse = AdminUpdateStatsAdminUpdateStatsPostResponses[keyof AdminUpdateStatsAdminUpdateStatsPostResponses];

export type GetMilestoneAnswerSessionsAdminMilestoneAnswerSessionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/milestone-answer-sessions/';
};

export type GetMilestoneAnswerSessionsAdminMilestoneAnswerSessionsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<MilestoneAnswerSession>;
};

export type GetMilestoneAnswerSessionsAdminMilestoneAnswerSessionsGetResponse = GetMilestoneAnswerSessionsAdminMilestoneAnswerSessionsGetResponses[keyof GetMilestoneAnswerSessionsAdminMilestoneAnswerSessionsGetResponses];

export type ModifyMilestoneAnswerSessionAdminMilestoneAnswerSessionsAnswerSessionIdPostData = {
    body?: never;
    path: {
        answer_session_id: number;
    };
    query: {
        suspicious: boolean;
    };
    url: '/admin/milestone-answer-sessions/{answer_session_id}';
};

export type ModifyMilestoneAnswerSessionAdminMilestoneAnswerSessionsAnswerSessionIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ModifyMilestoneAnswerSessionAdminMilestoneAnswerSessionsAnswerSessionIdPostError = ModifyMilestoneAnswerSessionAdminMilestoneAnswerSessionsAnswerSessionIdPostErrors[keyof ModifyMilestoneAnswerSessionAdminMilestoneAnswerSessionsAnswerSessionIdPostErrors];

export type ModifyMilestoneAnswerSessionAdminMilestoneAnswerSessionsAnswerSessionIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMilestoneAnswerSessionAnalysisAdminMilestoneAnswerSessionAnalysisAnswerSessionIdGetData = {
    body?: never;
    path: {
        answer_session_id: number;
    };
    query?: never;
    url: '/admin/milestone-answer-session-analysis/{answer_session_id}';
};

export type GetMilestoneAnswerSessionAnalysisAdminMilestoneAnswerSessionAnalysisAnswerSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMilestoneAnswerSessionAnalysisAdminMilestoneAnswerSessionAnalysisAnswerSessionIdGetError = GetMilestoneAnswerSessionAnalysisAdminMilestoneAnswerSessionAnalysisAnswerSessionIdGetErrors[keyof GetMilestoneAnswerSessionAnalysisAdminMilestoneAnswerSessionAnalysisAnswerSessionIdGetErrors];

export type GetMilestoneAnswerSessionAnalysisAdminMilestoneAnswerSessionAnalysisAnswerSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: MilestoneAnswerSessionAnalysis;
};

export type GetMilestoneAnswerSessionAnalysisAdminMilestoneAnswerSessionAnalysisAnswerSessionIdGetResponse = GetMilestoneAnswerSessionAnalysisAdminMilestoneAnswerSessionAnalysisAnswerSessionIdGetResponses[keyof GetMilestoneAnswerSessionAnalysisAdminMilestoneAnswerSessionAnalysisAnswerSessionIdGetResponses];

export type GetUserQuestionsAdminAdminUserQuestionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/user-questions/';
};

export type GetUserQuestionsAdminAdminUserQuestionsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<UserQuestionAdmin>;
};

export type GetUserQuestionsAdminAdminUserQuestionsGetResponse = GetUserQuestionsAdminAdminUserQuestionsGetResponses[keyof GetUserQuestionsAdminAdminUserQuestionsGetResponses];

export type CreateUserQuestionAdminUserQuestionsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/user-questions/';
};

export type CreateUserQuestionAdminUserQuestionsPostResponses = {
    /**
     * Successful Response
     */
    200: UserQuestionAdmin;
};

export type CreateUserQuestionAdminUserQuestionsPostResponse = CreateUserQuestionAdminUserQuestionsPostResponses[keyof CreateUserQuestionAdminUserQuestionsPostResponses];

export type UpdateUserQuestionAdminUserQuestionsPutData = {
    body: UserQuestionAdmin;
    path?: never;
    query?: never;
    url: '/admin/user-questions/';
};

export type UpdateUserQuestionAdminUserQuestionsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserQuestionAdminUserQuestionsPutError = UpdateUserQuestionAdminUserQuestionsPutErrors[keyof UpdateUserQuestionAdminUserQuestionsPutErrors];

export type UpdateUserQuestionAdminUserQuestionsPutResponses = {
    /**
     * Successful Response
     */
    200: UserQuestionAdmin;
};

export type UpdateUserQuestionAdminUserQuestionsPutResponse = UpdateUserQuestionAdminUserQuestionsPutResponses[keyof UpdateUserQuestionAdminUserQuestionsPutResponses];

export type DeleteUserQuestionAdminUserQuestionsUserQuestionIdDeleteData = {
    body?: never;
    path: {
        user_question_id: number;
    };
    query?: {
        /**
         * When true, shows what would be deleted without actually deleting
         */
        dry_run?: boolean;
    };
    url: '/admin/user-questions/{user_question_id}';
};

export type DeleteUserQuestionAdminUserQuestionsUserQuestionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserQuestionAdminUserQuestionsUserQuestionIdDeleteError = DeleteUserQuestionAdminUserQuestionsUserQuestionIdDeleteErrors[keyof DeleteUserQuestionAdminUserQuestionsUserQuestionIdDeleteErrors];

export type DeleteUserQuestionAdminUserQuestionsUserQuestionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteResponse;
};

export type DeleteUserQuestionAdminUserQuestionsUserQuestionIdDeleteResponse = DeleteUserQuestionAdminUserQuestionsUserQuestionIdDeleteResponses[keyof DeleteUserQuestionAdminUserQuestionsUserQuestionIdDeleteResponses];

export type OrderUserQuestionsAdminAdminUserQuestionsOrderPostData = {
    body: Array<ItemOrder>;
    path?: never;
    query?: never;
    url: '/admin/user-questions/order/';
};

export type OrderUserQuestionsAdminAdminUserQuestionsOrderPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrderUserQuestionsAdminAdminUserQuestionsOrderPostError = OrderUserQuestionsAdminAdminUserQuestionsOrderPostErrors[keyof OrderUserQuestionsAdminAdminUserQuestionsOrderPostErrors];

export type OrderUserQuestionsAdminAdminUserQuestionsOrderPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetChildQuestionsAdminAdminChildQuestionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/child-questions/';
};

export type GetChildQuestionsAdminAdminChildQuestionsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<ChildQuestionAdmin>;
};

export type GetChildQuestionsAdminAdminChildQuestionsGetResponse = GetChildQuestionsAdminAdminChildQuestionsGetResponses[keyof GetChildQuestionsAdminAdminChildQuestionsGetResponses];

export type CreateChildQuestionAdminChildQuestionsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/child-questions/';
};

export type CreateChildQuestionAdminChildQuestionsPostResponses = {
    /**
     * Successful Response
     */
    200: ChildQuestionAdmin;
};

export type CreateChildQuestionAdminChildQuestionsPostResponse = CreateChildQuestionAdminChildQuestionsPostResponses[keyof CreateChildQuestionAdminChildQuestionsPostResponses];

export type UpdateChildQuestionAdminChildQuestionsPutData = {
    body: ChildQuestionAdmin;
    path?: never;
    query?: never;
    url: '/admin/child-questions/';
};

export type UpdateChildQuestionAdminChildQuestionsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateChildQuestionAdminChildQuestionsPutError = UpdateChildQuestionAdminChildQuestionsPutErrors[keyof UpdateChildQuestionAdminChildQuestionsPutErrors];

export type UpdateChildQuestionAdminChildQuestionsPutResponses = {
    /**
     * Successful Response
     */
    200: ChildQuestionAdmin;
};

export type UpdateChildQuestionAdminChildQuestionsPutResponse = UpdateChildQuestionAdminChildQuestionsPutResponses[keyof UpdateChildQuestionAdminChildQuestionsPutResponses];

export type DeleteChildQuestionAdminChildQuestionsChildQuestionIdDeleteData = {
    body?: never;
    path: {
        child_question_id: number;
    };
    query?: {
        /**
         * When true, shows what would be deleted without actually deleting
         */
        dry_run?: boolean;
    };
    url: '/admin/child-questions/{child_question_id}';
};

export type DeleteChildQuestionAdminChildQuestionsChildQuestionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteChildQuestionAdminChildQuestionsChildQuestionIdDeleteError = DeleteChildQuestionAdminChildQuestionsChildQuestionIdDeleteErrors[keyof DeleteChildQuestionAdminChildQuestionsChildQuestionIdDeleteErrors];

export type DeleteChildQuestionAdminChildQuestionsChildQuestionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteResponse;
};

export type DeleteChildQuestionAdminChildQuestionsChildQuestionIdDeleteResponse = DeleteChildQuestionAdminChildQuestionsChildQuestionIdDeleteResponses[keyof DeleteChildQuestionAdminChildQuestionsChildQuestionIdDeleteResponses];

export type OrderChildQuestionsAdminAdminChildQuestionsOrderPostData = {
    body: Array<ItemOrder>;
    path?: never;
    query?: never;
    url: '/admin/child-questions/order/';
};

export type OrderChildQuestionsAdminAdminChildQuestionsOrderPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrderChildQuestionsAdminAdminChildQuestionsOrderPostError = OrderChildQuestionsAdminAdminChildQuestionsOrderPostErrors[keyof OrderChildQuestionsAdminAdminChildQuestionsOrderPostErrors];

export type OrderChildQuestionsAdminAdminChildQuestionsOrderPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAdminSettingsAdminSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/settings/';
};

export type GetAdminSettingsAdminSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: AdminSettingsPublic;
};

export type GetAdminSettingsAdminSettingsGetResponse = GetAdminSettingsAdminSettingsGetResponses[keyof GetAdminSettingsAdminSettingsGetResponses];

export type UpdateAdminSettingsAdminSettingsPutData = {
    body: AdminSettingsUpdate;
    path?: never;
    query?: never;
    url: '/admin/settings/';
};

export type UpdateAdminSettingsAdminSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAdminSettingsAdminSettingsPutError = UpdateAdminSettingsAdminSettingsPutErrors[keyof UpdateAdminSettingsAdminSettingsPutErrors];

export type UpdateAdminSettingsAdminSettingsPutResponses = {
    /**
     * Successful Response
     */
    200: AdminSettingsPublic;
};

export type UpdateAdminSettingsAdminSettingsPutResponse = UpdateAdminSettingsAdminSettingsPutResponses[keyof UpdateAdminSettingsAdminSettingsPutResponses];

export type GetUsersAdminUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/users/';
};

export type GetUsersAdminUsersGetResponses = {
    /**
     * Successful Response
     */
    200: Array<UserRead>;
};

export type GetUsersAdminUsersGetResponse = GetUsersAdminUsersGetResponses[keyof GetUsersAdminUsersGetResponses];

export type GetResearchGroupsAdminResearchGroupsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/research-groups/';
};

export type GetResearchGroupsAdminResearchGroupsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<ResearchGroup>;
};

export type GetResearchGroupsAdminResearchGroupsGetResponse = GetResearchGroupsAdminResearchGroupsGetResponses[keyof GetResearchGroupsAdminResearchGroupsGetResponses];

export type CreateResearchGroupAdminResearchGroupsUserIdPostData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/admin/research-groups/{user_id}';
};

export type CreateResearchGroupAdminResearchGroupsUserIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateResearchGroupAdminResearchGroupsUserIdPostError = CreateResearchGroupAdminResearchGroupsUserIdPostErrors[keyof CreateResearchGroupAdminResearchGroupsUserIdPostErrors];

export type CreateResearchGroupAdminResearchGroupsUserIdPostResponses = {
    /**
     * Successful Response
     */
    200: ResearchGroup;
};

export type CreateResearchGroupAdminResearchGroupsUserIdPostResponse = CreateResearchGroupAdminResearchGroupsUserIdPostResponses[keyof CreateResearchGroupAdminResearchGroupsUserIdPostResponses];

export type DeleteResearchGroupAdminResearchGroupsResearchGroupIdDeleteData = {
    body?: never;
    path: {
        research_group_id: number;
    };
    query?: never;
    url: '/admin/research-groups/{research_group_id}';
};

export type DeleteResearchGroupAdminResearchGroupsResearchGroupIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteResearchGroupAdminResearchGroupsResearchGroupIdDeleteError = DeleteResearchGroupAdminResearchGroupsResearchGroupIdDeleteErrors[keyof DeleteResearchGroupAdminResearchGroupsResearchGroupIdDeleteErrors];

export type DeleteResearchGroupAdminResearchGroupsResearchGroupIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ImportCsvDataAdminResearchImportCsvPostData = {
    body: BodyImportCsvDataAdminResearchImportCsvPost;
    path?: never;
    query?: never;
    url: '/admin/research/import-csv/';
};

export type ImportCsvDataAdminResearchImportCsvPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportCsvDataAdminResearchImportCsvPostError = ImportCsvDataAdminResearchImportCsvPostErrors[keyof ImportCsvDataAdminResearchImportCsvPostErrors];

export type ImportCsvDataAdminResearchImportCsvPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsersCurrentUserUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersCurrentUserUsersMeGetErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type UsersCurrentUserUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersCurrentUserUsersMeGetResponse = UsersCurrentUserUsersMeGetResponses[keyof UsersCurrentUserUsersMeGetResponses];

export type UsersPatchCurrentUserUsersMePatchData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersPatchCurrentUserUsersMePatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchCurrentUserUsersMePatchError = UsersPatchCurrentUserUsersMePatchErrors[keyof UsersPatchCurrentUserUsersMePatchErrors];

export type UsersPatchCurrentUserUsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchCurrentUserUsersMePatchResponse = UsersPatchCurrentUserUsersMePatchResponses[keyof UsersPatchCurrentUserUsersMePatchResponses];

export type UsersDeleteUserUsersIdDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersDeleteUserUsersIdDeleteErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserUsersIdDeleteError = UsersDeleteUserUsersIdDeleteErrors[keyof UsersDeleteUserUsersIdDeleteErrors];

export type UsersDeleteUserUsersIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserUsersIdDeleteResponse = UsersDeleteUserUsersIdDeleteResponses[keyof UsersDeleteUserUsersIdDeleteResponses];

export type UsersUserUsersIdGetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersUserUsersIdGetErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUserUsersIdGetError = UsersUserUsersIdGetErrors[keyof UsersUserUsersIdGetErrors];

export type UsersUserUsersIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUserUsersIdGetResponse = UsersUserUsersIdGetResponses[keyof UsersUserUsersIdGetResponses];

export type UsersPatchUserUsersIdPatchData = {
    body: UserUpdate;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersPatchUserUsersIdPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchUserUsersIdPatchError = UsersPatchUserUsersIdPatchErrors[keyof UsersPatchUserUsersIdPatchErrors];

export type UsersPatchUserUsersIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchUserUsersIdPatchResponse = UsersPatchUserUsersIdPatchResponses[keyof UsersPatchUserUsersIdPatchResponses];

export type GetChildrenUsersChildrenGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/children/';
};

export type GetChildrenUsersChildrenGetResponses = {
    /**
     * Successful Response
     */
    200: Array<ChildSummaryPublic>;
};

export type GetChildrenUsersChildrenGetResponse = GetChildrenUsersChildrenGetResponses[keyof GetChildrenUsersChildrenGetResponses];

export type CreateChildUsersChildrenPostData = {
    body: ChildCreate;
    path?: never;
    query?: never;
    url: '/users/children/';
};

export type CreateChildUsersChildrenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChildUsersChildrenPostError = CreateChildUsersChildrenPostErrors[keyof CreateChildUsersChildrenPostErrors];

export type CreateChildUsersChildrenPostResponses = {
    /**
     * Successful Response
     */
    200: ChildPublic;
};

export type CreateChildUsersChildrenPostResponse = CreateChildUsersChildrenPostResponses[keyof CreateChildUsersChildrenPostResponses];

export type UpdateChildUsersChildrenPutData = {
    body: ChildPublic;
    path?: never;
    query?: never;
    url: '/users/children/';
};

export type UpdateChildUsersChildrenPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateChildUsersChildrenPutError = UpdateChildUsersChildrenPutErrors[keyof UpdateChildUsersChildrenPutErrors];

export type UpdateChildUsersChildrenPutResponses = {
    /**
     * Successful Response
     */
    200: ChildPublic;
};

export type UpdateChildUsersChildrenPutResponse = UpdateChildUsersChildrenPutResponses[keyof UpdateChildUsersChildrenPutResponses];

export type DeleteChildUsersChildrenChildIdDeleteData = {
    body?: never;
    path: {
        child_id: number;
    };
    query?: {
        /**
         * When true, shows what would be deleted without actually deleting
         */
        dry_run?: boolean;
    };
    url: '/users/children/{child_id}';
};

export type DeleteChildUsersChildrenChildIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteChildUsersChildrenChildIdDeleteError = DeleteChildUsersChildrenChildIdDeleteErrors[keyof DeleteChildUsersChildrenChildIdDeleteErrors];

export type DeleteChildUsersChildrenChildIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteResponse;
};

export type DeleteChildUsersChildrenChildIdDeleteResponse = DeleteChildUsersChildrenChildIdDeleteResponses[keyof DeleteChildUsersChildrenChildIdDeleteResponses];

export type GetChildUsersChildrenChildIdGetData = {
    body?: never;
    path: {
        child_id: number;
    };
    query?: never;
    url: '/users/children/{child_id}';
};

export type GetChildUsersChildrenChildIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChildUsersChildrenChildIdGetError = GetChildUsersChildrenChildIdGetErrors[keyof GetChildUsersChildrenChildIdGetErrors];

export type GetChildUsersChildrenChildIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChildPublic;
};

export type GetChildUsersChildrenChildIdGetResponse = GetChildUsersChildrenChildIdGetResponses[keyof GetChildUsersChildrenChildIdGetResponses];

export type DeleteChildImageUsersChildrenImagesChildIdDeleteData = {
    body?: never;
    path: {
        child_id: number;
    };
    query?: never;
    url: '/users/children-images/{child_id}';
};

export type DeleteChildImageUsersChildrenImagesChildIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteChildImageUsersChildrenImagesChildIdDeleteError = DeleteChildImageUsersChildrenImagesChildIdDeleteErrors[keyof DeleteChildImageUsersChildrenImagesChildIdDeleteErrors];

export type DeleteChildImageUsersChildrenImagesChildIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetChildImageUsersChildrenImagesChildIdGetData = {
    body?: never;
    path: {
        child_id: number;
    };
    query?: never;
    url: '/users/children-images/{child_id}';
};

export type GetChildImageUsersChildrenImagesChildIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChildImageUsersChildrenImagesChildIdGetError = GetChildImageUsersChildrenImagesChildIdGetErrors[keyof GetChildImageUsersChildrenImagesChildIdGetErrors];

export type GetChildImageUsersChildrenImagesChildIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadChildImageUsersChildrenImagesChildIdPutData = {
    body: BodyUploadChildImageUsersChildrenImagesChildIdPut;
    path: {
        child_id: number;
    };
    query?: never;
    url: '/users/children-images/{child_id}';
};

export type UploadChildImageUsersChildrenImagesChildIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadChildImageUsersChildrenImagesChildIdPutError = UploadChildImageUsersChildrenImagesChildIdPutErrors[keyof UploadChildImageUsersChildrenImagesChildIdPutErrors];

export type UploadChildImageUsersChildrenImagesChildIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentMilestoneAnswerSessionUsersMilestoneAnswersChildIdGetData = {
    body?: never;
    path: {
        child_id: number;
    };
    query?: never;
    url: '/users/milestone-answers/{child_id}';
};

export type GetCurrentMilestoneAnswerSessionUsersMilestoneAnswersChildIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCurrentMilestoneAnswerSessionUsersMilestoneAnswersChildIdGetError = GetCurrentMilestoneAnswerSessionUsersMilestoneAnswersChildIdGetErrors[keyof GetCurrentMilestoneAnswerSessionUsersMilestoneAnswersChildIdGetErrors];

export type GetCurrentMilestoneAnswerSessionUsersMilestoneAnswersChildIdGetResponses = {
    /**
     * Successful Response
     */
    200: MilestoneAnswerSessionPublic;
};

export type GetCurrentMilestoneAnswerSessionUsersMilestoneAnswersChildIdGetResponse = GetCurrentMilestoneAnswerSessionUsersMilestoneAnswersChildIdGetResponses[keyof GetCurrentMilestoneAnswerSessionUsersMilestoneAnswersChildIdGetResponses];

export type UpdateMilestoneAnswerUsersMilestoneAnswersMilestoneAnswerSessionIdPutData = {
    body: MilestoneAnswerPublic;
    path: {
        milestone_answer_session_id: number;
    };
    query?: never;
    url: '/users/milestone-answers/{milestone_answer_session_id}';
};

export type UpdateMilestoneAnswerUsersMilestoneAnswersMilestoneAnswerSessionIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMilestoneAnswerUsersMilestoneAnswersMilestoneAnswerSessionIdPutError = UpdateMilestoneAnswerUsersMilestoneAnswersMilestoneAnswerSessionIdPutErrors[keyof UpdateMilestoneAnswerUsersMilestoneAnswersMilestoneAnswerSessionIdPutErrors];

export type UpdateMilestoneAnswerUsersMilestoneAnswersMilestoneAnswerSessionIdPutResponses = {
    /**
     * Successful Response
     */
    200: MilestoneAnswerResponse;
};

export type UpdateMilestoneAnswerUsersMilestoneAnswersMilestoneAnswerSessionIdPutResponse = UpdateMilestoneAnswerUsersMilestoneAnswersMilestoneAnswerSessionIdPutResponses[keyof UpdateMilestoneAnswerUsersMilestoneAnswersMilestoneAnswerSessionIdPutResponses];

export type GetCurrentUserAnswersUsersUserAnswersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/user-answers/';
};

export type GetCurrentUserAnswersUsersUserAnswersGetResponses = {
    /**
     * Successful Response
     */
    200: Array<UserAnswerPublic>;
};

export type GetCurrentUserAnswersUsersUserAnswersGetResponse = GetCurrentUserAnswersUsersUserAnswersGetResponses[keyof GetCurrentUserAnswersUsersUserAnswersGetResponses];

export type UpdateCurrentUserAnswersUsersUserAnswersPutData = {
    body: Array<UserAnswerPublic>;
    path?: never;
    query?: never;
    url: '/users/user-answers/';
};

export type UpdateCurrentUserAnswersUsersUserAnswersPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentUserAnswersUsersUserAnswersPutError = UpdateCurrentUserAnswersUsersUserAnswersPutErrors[keyof UpdateCurrentUserAnswersUsersUserAnswersPutErrors];

export type UpdateCurrentUserAnswersUsersUserAnswersPutResponses = {
    /**
     * Successful Response
     */
    200: Array<UserAnswerPublic>;
};

export type UpdateCurrentUserAnswersUsersUserAnswersPutResponse = UpdateCurrentUserAnswersUsersUserAnswersPutResponses[keyof UpdateCurrentUserAnswersUsersUserAnswersPutResponses];

export type GetCurrentChildAnswersUsersChildrenAnswersChildIdGetData = {
    body?: never;
    path: {
        child_id: number;
    };
    query?: never;
    url: '/users/children-answers/{child_id}';
};

export type GetCurrentChildAnswersUsersChildrenAnswersChildIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCurrentChildAnswersUsersChildrenAnswersChildIdGetError = GetCurrentChildAnswersUsersChildrenAnswersChildIdGetErrors[keyof GetCurrentChildAnswersUsersChildrenAnswersChildIdGetErrors];

export type GetCurrentChildAnswersUsersChildrenAnswersChildIdGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: ChildAnswerPublic;
    };
};

export type GetCurrentChildAnswersUsersChildrenAnswersChildIdGetResponse = GetCurrentChildAnswersUsersChildrenAnswersChildIdGetResponses[keyof GetCurrentChildAnswersUsersChildrenAnswersChildIdGetResponses];

export type UpdateCurrentChildAnswersUsersChildrenAnswersChildIdPutData = {
    body: {
        [key: string]: ChildAnswerPublic;
    };
    path: {
        child_id: number;
    };
    query?: never;
    url: '/users/children-answers/{child_id}';
};

export type UpdateCurrentChildAnswersUsersChildrenAnswersChildIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentChildAnswersUsersChildrenAnswersChildIdPutError = UpdateCurrentChildAnswersUsersChildrenAnswersChildIdPutErrors[keyof UpdateCurrentChildAnswersUsersChildrenAnswersChildIdPutErrors];

export type UpdateCurrentChildAnswersUsersChildrenAnswersChildIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCompletedMilestoneAnswerSessionsUsersMilestoneAnswersSessionsChildIdGetData = {
    body?: never;
    path: {
        child_id: number;
    };
    query?: never;
    url: '/users/milestone-answers-sessions/{child_id}';
};

export type GetCompletedMilestoneAnswerSessionsUsersMilestoneAnswersSessionsChildIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCompletedMilestoneAnswerSessionsUsersMilestoneAnswersSessionsChildIdGetError = GetCompletedMilestoneAnswerSessionsUsersMilestoneAnswersSessionsChildIdGetErrors[keyof GetCompletedMilestoneAnswerSessionsUsersMilestoneAnswersSessionsChildIdGetErrors];

export type GetCompletedMilestoneAnswerSessionsUsersMilestoneAnswersSessionsChildIdGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: MilestoneAnswerSessionPublic;
    };
};

export type GetCompletedMilestoneAnswerSessionsUsersMilestoneAnswersSessionsChildIdGetResponse = GetCompletedMilestoneAnswerSessionsUsersMilestoneAnswersSessionsChildIdGetResponses[keyof GetCompletedMilestoneAnswerSessionsUsersMilestoneAnswersSessionsChildIdGetResponses];

export type GetMilestonegroupsForSessionUsersFeedbackAnswersessionAnswersessionIdGetData = {
    body?: never;
    path: {
        answersession_id: number;
    };
    query?: never;
    url: '/users/feedback/answersession={answersession_id}';
};

export type GetMilestonegroupsForSessionUsersFeedbackAnswersessionAnswersessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMilestonegroupsForSessionUsersFeedbackAnswersessionAnswersessionIdGetError = GetMilestonegroupsForSessionUsersFeedbackAnswersessionAnswersessionIdGetErrors[keyof GetMilestonegroupsForSessionUsersFeedbackAnswersessionAnswersessionIdGetErrors];

export type GetMilestonegroupsForSessionUsersFeedbackAnswersessionAnswersessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: MilestoneGroupPublic;
    };
};

export type GetMilestonegroupsForSessionUsersFeedbackAnswersessionAnswersessionIdGetResponse = GetMilestonegroupsForSessionUsersFeedbackAnswersessionAnswersessionIdGetResponses[keyof GetMilestonegroupsForSessionUsersFeedbackAnswersessionAnswersessionIdGetResponses];

export type GetSummaryFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdSummaryGetData = {
    body?: never;
    path: {
        answersession_id: number;
    };
    query?: never;
    url: '/users/feedback/answersession={answersession_id}/summary';
};

export type GetSummaryFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdSummaryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSummaryFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdSummaryGetError = GetSummaryFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdSummaryGetErrors[keyof GetSummaryFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdSummaryGetErrors];

export type GetSummaryFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type GetSummaryFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdSummaryGetResponse = GetSummaryFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdSummaryGetResponses[keyof GetSummaryFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdSummaryGetResponses];

export type GetDetailedFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdDetailedGetData = {
    body?: never;
    path: {
        answersession_id: number;
    };
    query?: never;
    url: '/users/feedback/answersession={answersession_id}/detailed';
};

export type GetDetailedFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdDetailedGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDetailedFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdDetailedGetError = GetDetailedFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdDetailedGetErrors[keyof GetDetailedFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdDetailedGetErrors];

export type GetDetailedFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdDetailedGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: {
            [key: string]: number;
        };
    };
};

export type GetDetailedFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdDetailedGetResponse = GetDetailedFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdDetailedGetResponses[keyof GetDetailedFeedbackForAnswersessionUsersFeedbackAnswersessionAnswersessionIdDetailedGetResponses];

export type AuthCookieLoginAuthLoginPostData = {
    body: BodyAuthCookieLoginAuthLoginPost;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthCookieLoginAuthLoginPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthCookieLoginAuthLoginPostError = AuthCookieLoginAuthLoginPostErrors[keyof AuthCookieLoginAuthLoginPostErrors];

export type AuthCookieLoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
    /**
     * No Content
     */
    204: void;
};

export type AuthCookieLoginAuthLoginPostResponse = AuthCookieLoginAuthLoginPostResponses[keyof AuthCookieLoginAuthLoginPostResponses];

export type AuthCookieLogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthCookieLogoutAuthLogoutPostErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type AuthCookieLogoutAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
    /**
     * No Content
     */
    204: void;
};

export type AuthCookieLogoutAuthLogoutPostResponse = AuthCookieLogoutAuthLogoutPostResponses[keyof AuthCookieLogoutAuthLogoutPostResponses];

export type RegisterRegisterAuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterRegisterAuthRegisterPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterRegisterAuthRegisterPostError = RegisterRegisterAuthRegisterPostErrors[keyof RegisterRegisterAuthRegisterPostErrors];

export type RegisterRegisterAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterRegisterAuthRegisterPostResponse = RegisterRegisterAuthRegisterPostResponses[keyof RegisterRegisterAuthRegisterPostResponses];

export type ResetForgotPasswordAuthForgotPasswordPostData = {
    body: BodyResetForgotPasswordAuthForgotPasswordPost;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type ResetForgotPasswordAuthForgotPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetForgotPasswordAuthForgotPasswordPostError = ResetForgotPasswordAuthForgotPasswordPostErrors[keyof ResetForgotPasswordAuthForgotPasswordPostErrors];

export type ResetForgotPasswordAuthForgotPasswordPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ResetResetPasswordAuthResetPasswordPostData = {
    body: BodyResetResetPasswordAuthResetPasswordPost;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetResetPasswordAuthResetPasswordPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetResetPasswordAuthResetPasswordPostError = ResetResetPasswordAuthResetPasswordPostErrors[keyof ResetResetPasswordAuthResetPasswordPostErrors];

export type ResetResetPasswordAuthResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyRequestTokenAuthRequestVerifyTokenPostData = {
    body: BodyVerifyRequestTokenAuthRequestVerifyTokenPost;
    path?: never;
    query?: never;
    url: '/auth/request-verify-token';
};

export type VerifyRequestTokenAuthRequestVerifyTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyRequestTokenAuthRequestVerifyTokenPostError = VerifyRequestTokenAuthRequestVerifyTokenPostErrors[keyof VerifyRequestTokenAuthRequestVerifyTokenPostErrors];

export type VerifyRequestTokenAuthRequestVerifyTokenPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type VerifyVerifyAuthVerifyPostData = {
    body: BodyVerifyVerifyAuthVerifyPost;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type VerifyVerifyAuthVerifyPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyVerifyAuthVerifyPostError = VerifyVerifyAuthVerifyPostErrors[keyof VerifyVerifyAuthVerifyPostErrors];

export type VerifyVerifyAuthVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type VerifyVerifyAuthVerifyPostResponse = VerifyVerifyAuthVerifyPostResponses[keyof VerifyVerifyAuthVerifyPostResponses];

export type GetResearchDataResearchDataGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/research/data/';
};

export type GetResearchDataResearchDataGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetResearchNamesResearchNamesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/research/names/';
};

export type GetResearchNamesResearchNamesGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: {
            [key: string]: string;
        };
    };
};

export type GetResearchNamesResearchNamesGetResponse = GetResearchNamesResearchNamesGetResponses[keyof GetResearchNamesResearchNamesGetResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};