// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AdminSettingsPublic
 */
export type AdminSettingsPublic = {
    /**
     * Hide Milestone Feedback
     */
    hide_milestone_feedback: boolean;
    /**
     * Hide Milestone Group Feedback
     */
    hide_milestone_group_feedback: boolean;
    /**
     * Hide All Feedback
     */
    hide_all_feedback: boolean;
};

/**
 * AdminSettingsUpdate
 */
export type AdminSettingsUpdate = {
    /**
     * Hide Milestone Feedback
     */
    hide_milestone_feedback?: boolean | null;
    /**
     * Hide Milestone Group Feedback
     */
    hide_milestone_group_feedback?: boolean | null;
    /**
     * Hide All Feedback
     */
    hide_all_feedback?: boolean | null;
};

/**
 * Body_create_document
 */
export type BodyCreateDocument = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_import_csv_data
 */
export type BodyImportCsvData = {
    /**
     * Additional Data File
     *
     * Additional data CSV file
     */
    additional_data_file: Blob | File;
    /**
     * Labels File
     *
     * Labels CSV file
     */
    labels_file?: Blob | File;
    /**
     * Research Group Id
     *
     * Researcher code applied to all imported users
     */
    research_group_id?: number | null;
};

/**
 * Body_reset:forgot_password
 */
export type BodyResetForgotPassword = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_reset:reset_password
 */
export type BodyResetResetPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Body_submit_milestone_image
 */
export type BodySubmitMilestoneImage = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_child_image
 */
export type BodyUploadChildImage = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_milestone_group_image
 */
export type BodyUploadMilestoneGroupImage = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_milestone_image
 */
export type BodyUploadMilestoneImage = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_verify:request-token
 */
export type BodyVerifyRequestToken = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_verify:verify
 */
export type BodyVerifyVerify = {
    /**
     * Token
     */
    token: string;
};

/**
 * CalendarEventCreate
 */
export type CalendarEventCreate = {
    /**
     * Title
     */
    title?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * External Link
     */
    external_link?: string;
    /**
     * Event Date
     */
    event_date: string;
};

/**
 * CalendarEventRead
 */
export type CalendarEventRead = {
    /**
     * Title
     */
    title?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * External Link
     */
    external_link?: string;
    /**
     * Event Date
     */
    event_date: string;
    /**
     * Id
     */
    id: number;
};

/**
 * CalendarEventUpdate
 */
export type CalendarEventUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * External Link
     */
    external_link?: string | null;
    /**
     * Event Date
     */
    event_date?: string | null;
};

/**
 * ChildAnswerAnalysisFlag
 */
export type ChildAnswerAnalysisFlag = {
    /**
     * Question Id
     */
    question_id: number;
    /**
     * Question
     */
    question: {
        [key: string]: string;
    };
    /**
     * Answer
     */
    answer: string;
    /**
     * Additional Answer
     */
    additional_answer: string | null;
};

/**
 * ChildAnswerPublic
 */
export type ChildAnswerPublic = {
    /**
     * Answer
     */
    answer: string;
    /**
     * Additional Answer
     */
    additional_answer: string | null;
    /**
     * Question Id
     */
    question_id: number;
};

/**
 * ChildCreate
 */
export type ChildCreate = {
    /**
     * Name
     */
    name?: string;
    /**
     * Birth Year
     */
    birth_year: number;
    /**
     * Birth Month
     */
    birth_month: number;
    /**
     * Color
     */
    color?: string | null;
};

/**
 * ChildPublic
 */
export type ChildPublic = {
    /**
     * Name
     */
    name?: string;
    /**
     * Birth Year
     */
    birth_year: number;
    /**
     * Birth Month
     */
    birth_month: number;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Has Image
     */
    has_image: boolean;
};

/**
 * ChildQuestionAdmin
 */
export type ChildQuestionAdmin = {
    /**
     * Order
     */
    order?: number;
    /**
     * Component
     */
    component?: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Options
     */
    options?: string;
    /**
     * Additional Option
     */
    additional_option?: string;
    /**
     * Required
     */
    required?: boolean;
    /**
     * Name
     */
    name?: string;
    /**
     * Visibility
     */
    visibility?: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text?: {
        [key: string]: ChildQuestionText;
    };
};

/**
 * ChildQuestionPublic
 */
export type ChildQuestionPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Component
     */
    component?: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Text
     */
    text?: {
        [key: string]: QuestionTextPublic;
    };
    /**
     * Additional Option
     */
    additional_option?: string;
    /**
     * Required
     */
    required?: boolean;
    /**
     * Name
     */
    name?: string;
};

/**
 * ChildQuestionText
 */
export type ChildQuestionText = {
    /**
     * Question
     */
    question?: string;
    /**
     * Options Json
     */
    options_json?: string;
    /**
     * Options
     */
    options?: string;
    /**
     * Child Question Id
     */
    child_question_id?: number | null;
    /**
     * Lang Id
     */
    lang_id?: string | null;
};

/**
 * ChildSummaryPublic
 */
export type ChildSummaryPublic = {
    /**
     * Name
     */
    name?: string;
    /**
     * Birth Year
     */
    birth_year: number;
    /**
     * Birth Month
     */
    birth_month: number;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Has Image
     */
    has_image: boolean;
    /**
     * Active Answer Session
     */
    active_answer_session: boolean;
    /**
     * Session Progress
     */
    session_progress: number;
    /**
     * Session Remaining Seconds
     */
    session_remaining_seconds: number;
};

/**
 * DeleteResponse
 */
export type DeleteResponse = {
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Dry Run
     */
    dry_run: boolean;
    /**
     * Children
     */
    children: {
        [key: string]: number;
    };
    /**
     * Error
     *
     * Error message when present
     */
    error?: string | null;
};

/**
 * DocumentAdmin
 */
export type DocumentAdmin = {
    /**
     * Title
     */
    title?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Filename
     */
    filename?: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Uploaded By User Id
     */
    uploaded_by_user_id: number;
};

/**
 * DocumentCreate
 */
export type DocumentCreate = {
    /**
     * Title
     */
    title?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Filename
     */
    filename?: string;
};

/**
 * DocumentPublic
 */
export type DocumentPublic = {
    /**
     * Title
     */
    title?: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Filename
     */
    filename?: string;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Uploaded By User Id
     */
    uploaded_by_user_id: number;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
    /**
     * Detail
     */
    detail: string | {
        [key: string]: string;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImportCsvResponse
 */
export type ImportCsvResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Children Imported
     */
    children_imported: number;
};

/**
 * ItemOrder
 */
export type ItemOrder = {
    /**
     * Id
     */
    id: number;
    /**
     * Order
     */
    order: number;
};

/**
 * Language
 */
export type Language = {
    /**
     * Id
     */
    id: string;
};

/**
 * MilestoneAdmin
 */
export type MilestoneAdmin = {
    /**
     * Id
     */
    id: number;
    /**
     * Group Id
     */
    group_id: number;
    /**
     * Order
     */
    order: number;
    /**
     * Expected Age Months
     */
    expected_age_months: number;
    /**
     * Relevant Age Min
     */
    relevant_age_min: number;
    /**
     * Relevant Age Max
     */
    relevant_age_max: number;
    /**
     * Text
     */
    text: {
        [key: string]: MilestoneText;
    };
    /**
     * Images
     */
    images: Array<MilestoneImage>;
    /**
     * Name
     */
    name: string;
};

/**
 * MilestoneAgeScore
 */
export type MilestoneAgeScore = {
    /**
     * Milestone Id
     */
    milestone_id?: number | null;
    /**
     * Age
     */
    age: number;
    /**
     * C0
     */
    c0: number;
    /**
     * C1
     */
    c1: number;
    /**
     * C2
     */
    c2: number;
    /**
     * C3
     */
    c3: number;
};

/**
 * MilestoneAgeScoreCollectionPublic
 */
export type MilestoneAgeScoreCollectionPublic = {
    /**
     * Milestone Id
     */
    milestone_id: number;
    /**
     * Expected Age
     */
    expected_age: number;
    /**
     * Relevant Age Min
     */
    relevant_age_min: number;
    /**
     * Relevant Age Max
     */
    relevant_age_max: number;
    /**
     * Scores
     */
    scores: Array<MilestoneAgeScore>;
};

/**
 * MilestoneAnswerAnalysis
 */
export type MilestoneAnswerAnalysis = {
    /**
     * Milestone Id
     */
    milestone_id: number;
    /**
     * Milestone Title
     */
    milestone_title: {
        [key: string]: string;
    };
    /**
     * Milestone Order
     */
    milestone_order: number;
    /**
     * Milestone Group Id
     */
    milestone_group_id: number;
    /**
     * Milestone Group Name
     */
    milestone_group_name: {
        [key: string]: string;
    };
    /**
     * Milestone Group Order
     */
    milestone_group_order: number;
    /**
     * Answer
     */
    answer: number;
    /**
     * Avg Answer
     */
    avg_answer: number;
    /**
     * Stddev Answer
     */
    stddev_answer: number;
};

/**
 * MilestoneAnswerPublic
 */
export type MilestoneAnswerPublic = {
    /**
     * Milestone Id
     */
    milestone_id: number;
    /**
     * Answer
     */
    answer: number;
};

/**
 * MilestoneAnswerResponse
 */
export type MilestoneAnswerResponse = {
    answer: MilestoneAnswerPublic;
    /**
     * Session Completed
     */
    session_completed: boolean;
};

/**
 * MilestoneAnswerSession
 */
export type MilestoneAnswerSession = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Child Id
     */
    child_id: number;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expired
     */
    expired: boolean;
    /**
     * Completed
     */
    completed: boolean;
    /**
     * Included In Statistics
     */
    included_in_statistics: boolean;
    /**
     * Suspicious State
     */
    suspicious_state?: string;
};

/**
 * MilestoneAnswerSessionAnalysis
 */
export type MilestoneAnswerSessionAnalysis = {
    /**
     * Child Age
     */
    child_age: number;
    /**
     * Rms
     */
    rms: number;
    /**
     * Answers
     */
    answers: Array<MilestoneAnswerAnalysis>;
    /**
     * Child Answer Flags
     */
    child_answer_flags: Array<ChildAnswerAnalysisFlag>;
};

/**
 * MilestoneAnswerSessionPublic
 */
export type MilestoneAnswerSessionPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Child Id
     */
    child_id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Answers
     */
    answers: {
        [key: string]: MilestoneAnswerPublic;
    };
};

/**
 * MilestoneGroupAdmin
 */
export type MilestoneGroupAdmin = {
    /**
     * Id
     */
    id: number;
    /**
     * Order
     */
    order: number;
    /**
     * Text
     */
    text: {
        [key: string]: MilestoneGroupText;
    };
    /**
     * Milestones
     */
    milestones: Array<MilestoneAdmin>;
};

/**
 * MilestoneGroupPublic
 */
export type MilestoneGroupPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text: {
        [key: string]: MilestoneGroupTextPublic;
    };
    /**
     * Milestones
     */
    milestones: Array<MilestonePublic>;
};

/**
 * MilestoneGroupText
 */
export type MilestoneGroupText = {
    /**
     * Title
     */
    title?: string;
    /**
     * Desc
     */
    desc?: string;
    /**
     * Group Id
     */
    group_id?: number | null;
    /**
     * Lang Id
     */
    lang_id?: string | null;
};

/**
 * MilestoneGroupTextPublic
 */
export type MilestoneGroupTextPublic = {
    /**
     * Title
     */
    title?: string;
    /**
     * Desc
     */
    desc?: string;
};

/**
 * MilestoneImage
 */
export type MilestoneImage = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Milestone Id
     */
    milestone_id?: number | null;
};

/**
 * MilestoneImagePublic
 */
export type MilestoneImagePublic = {
    /**
     * Id
     */
    id: number;
};

/**
 * MilestonePublic
 */
export type MilestonePublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text: {
        [key: string]: MilestoneTextPublic;
    };
    /**
     * Images
     */
    images: Array<MilestoneImagePublic>;
    /**
     * Name
     */
    name: string;
};

/**
 * MilestoneText
 */
export type MilestoneText = {
    /**
     * Title
     */
    title?: string;
    /**
     * Desc
     */
    desc?: string;
    /**
     * Obs
     */
    obs?: string;
    /**
     * Help
     */
    help?: string;
    /**
     * Importance
     */
    importance?: string;
    /**
     * Milestone Id
     */
    milestone_id?: number | null;
    /**
     * Lang Id
     */
    lang_id?: string | null;
};

/**
 * MilestoneTextPublic
 */
export type MilestoneTextPublic = {
    /**
     * Title
     */
    title?: string;
    /**
     * Desc
     */
    desc?: string;
    /**
     * Obs
     */
    obs?: string;
    /**
     * Help
     */
    help?: string;
    /**
     * Importance
     */
    importance?: string;
};

/**
 * QuestionTextPublic
 */
export type QuestionTextPublic = {
    /**
     * Question
     */
    question?: string;
    /**
     * Options Json
     */
    options_json?: string;
    /**
     * Options
     */
    options?: string;
};

/**
 * ResearchGroup
 */
export type ResearchGroup = {
    /**
     * Id
     */
    id: number;
};

/**
 * SessionReauthentication
 */
export type SessionReauthentication = {
    /**
     * Password
     */
    password: string;
};

/**
 * StatisticsUpdateResult
 *
 * Result of a statistics recalculation, used to build a localized summary in the UI.
 */
export type StatisticsUpdateResult = {
    /**
     * Answer Sessions
     */
    answer_sessions: number;
    /**
     * Answers
     */
    answers: number;
    /**
     * Runtime Seconds
     */
    runtime_seconds: number;
};

/**
 * SubmittedMilestoneImagePublic
 */
export type SubmittedMilestoneImagePublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Milestone Id
     */
    milestone_id: number;
    /**
     * User Id
     */
    user_id: number;
};

/**
 * UserAnswerPublic
 */
export type UserAnswerPublic = {
    /**
     * Answer
     */
    answer: string;
    /**
     * Additional Answer
     */
    additional_answer: string | null;
    /**
     * Question Id
     */
    question_id: number;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
    /**
     * Is Researcher
     */
    is_researcher?: boolean | null;
    /**
     * Full Data Access
     */
    full_data_access?: boolean | null;
    /**
     * Research Group Id
     */
    research_group_id?: number | null;
};

/**
 * UserQuestionAdmin
 */
export type UserQuestionAdmin = {
    /**
     * Order
     */
    order?: number;
    /**
     * Component
     */
    component?: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Options
     */
    options?: string;
    /**
     * Additional Option
     */
    additional_option?: string;
    /**
     * Required
     */
    required?: boolean;
    /**
     * Name
     */
    name?: string;
    /**
     * Visibility
     */
    visibility?: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text?: {
        [key: string]: UserQuestionText;
    };
};

/**
 * UserQuestionPublic
 */
export type UserQuestionPublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Component
     */
    component?: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Text
     */
    text?: {
        [key: string]: QuestionTextPublic;
    };
    /**
     * Additional Option
     */
    additional_option?: string;
    /**
     * Required
     */
    required?: boolean;
    /**
     * Name
     */
    name?: string;
};

/**
 * UserQuestionText
 */
export type UserQuestionText = {
    /**
     * Question
     */
    question?: string;
    /**
     * Options Json
     */
    options_json?: string;
    /**
     * Options
     */
    options?: string;
    /**
     * User Question Id
     */
    user_question_id?: number | null;
    /**
     * Lang Id
     */
    lang_id?: string | null;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Is Verified
     */
    is_verified?: boolean;
    /**
     * Is Researcher
     */
    is_researcher: boolean;
    /**
     * Full Data Access
     */
    full_data_access: boolean;
    /**
     * Research Group Id
     */
    research_group_id: number;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Password
     */
    password?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
    /**
     * Is Researcher
     */
    is_researcher?: boolean | null;
    /**
     * Full Data Access
     */
    full_data_access?: boolean | null;
    /**
     * Research Group Id
     */
    research_group_id?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * Body_auth:cookie.login
 */
export type Login = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

export type GetEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/events/';
};

export type GetEventsResponses = {
    /**
     * Response Get Events
     *
     * Successful Response
     */
    200: Array<CalendarEventRead>;
};

export type GetEventsResponse = GetEventsResponses[keyof GetEventsResponses];

export type GetPublicDocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/documents/';
};

export type GetPublicDocumentsResponses = {
    /**
     * Response Get Public Documents
     *
     * Successful Response
     */
    200: Array<DocumentPublic>;
};

export type GetPublicDocumentsResponse = GetPublicDocumentsResponses[keyof GetPublicDocumentsResponses];

export type GetLanguagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/languages/';
};

export type GetLanguagesResponses = {
    /**
     * Response Get Languages
     *
     * Successful Response
     */
    200: Array<string>;
};

export type GetLanguagesResponse = GetLanguagesResponses[keyof GetLanguagesResponses];

export type GetMilestonesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/milestones/';
};

export type GetMilestonesResponses = {
    /**
     * Response Get Milestones
     *
     * Successful Response
     */
    200: Array<MilestonePublic>;
};

export type GetMilestonesResponse = GetMilestonesResponses[keyof GetMilestonesResponses];

export type GetMilestoneData = {
    body?: never;
    path: {
        /**
         * Milestone Id
         */
        milestone_id: number;
    };
    query?: never;
    url: '/milestones/{milestone_id}';
};

export type GetMilestoneErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMilestoneError = GetMilestoneErrors[keyof GetMilestoneErrors];

export type GetMilestoneResponses = {
    /**
     * Successful Response
     */
    200: MilestonePublic;
};

export type GetMilestoneResponse = GetMilestoneResponses[keyof GetMilestoneResponses];

export type GetMilestoneGroupsData = {
    body?: never;
    path: {
        /**
         * Child Id
         */
        child_id: number;
    };
    query?: never;
    url: '/milestone-groups/{child_id}';
};

export type GetMilestoneGroupsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMilestoneGroupsError = GetMilestoneGroupsErrors[keyof GetMilestoneGroupsErrors];

export type GetMilestoneGroupsResponses = {
    /**
     * Response Get Milestone Groups
     *
     * Successful Response
     */
    200: Array<MilestoneGroupPublic>;
};

export type GetMilestoneGroupsResponse = GetMilestoneGroupsResponses[keyof GetMilestoneGroupsResponses];

export type SubmitMilestoneImageData = {
    body: BodySubmitMilestoneImage;
    path: {
        /**
         * Milestone Id
         */
        milestone_id: number;
    };
    query?: never;
    url: '/submitted-milestone-images/{milestone_id}';
};

export type SubmitMilestoneImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitMilestoneImageError = SubmitMilestoneImageErrors[keyof SubmitMilestoneImageErrors];

export type SubmitMilestoneImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserQuestionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user-questions/';
};

export type GetUserQuestionsResponses = {
    /**
     * Response Get User Questions
     *
     * Successful Response
     */
    200: Array<UserQuestionPublic>;
};

export type GetUserQuestionsResponse = GetUserQuestionsResponses[keyof GetUserQuestionsResponses];

export type GetChildQuestionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/child-questions/';
};

export type GetChildQuestionsResponses = {
    /**
     * Response Get Child Questions
     *
     * Successful Response
     */
    200: Array<ChildQuestionPublic>;
};

export type GetChildQuestionsResponse = GetChildQuestionsResponses[keyof GetChildQuestionsResponses];

export type CreateEventData = {
    body: CalendarEventCreate;
    path?: never;
    query?: never;
    url: '/admin/calendarevents/';
};

export type CreateEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEventError = CreateEventErrors[keyof CreateEventErrors];

export type CreateEventResponses = {
    /**
     * Successful Response
     */
    200: CalendarEventRead;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type DeleteEventData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: number;
    };
    query?: never;
    url: '/admin/calendarevents/{event_id}';
};

export type DeleteEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEventError = DeleteEventErrors[keyof DeleteEventErrors];

export type DeleteEventResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateEventData = {
    body: CalendarEventUpdate;
    path: {
        /**
         * Event Id
         */
        event_id: number;
    };
    query?: never;
    url: '/admin/calendarevents/{event_id}';
};

export type UpdateEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEventError = UpdateEventErrors[keyof UpdateEventErrors];

export type UpdateEventResponses = {
    /**
     * Successful Response
     */
    200: CalendarEventRead;
};

export type UpdateEventResponse = UpdateEventResponses[keyof UpdateEventResponses];

export type GetDocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/documents/';
};

export type GetDocumentsResponses = {
    /**
     * Response Get Documents
     *
     * Successful Response
     */
    200: Array<DocumentAdmin>;
};

export type GetDocumentsResponse = GetDocumentsResponses[keyof GetDocumentsResponses];

export type CreateDocumentData = {
    body: BodyCreateDocument;
    path?: never;
    query?: never;
    url: '/admin/documents/';
};

export type CreateDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDocumentError = CreateDocumentErrors[keyof CreateDocumentErrors];

export type CreateDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentAdmin;
};

export type CreateDocumentResponse = CreateDocumentResponses[keyof CreateDocumentResponses];

export type DeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: number;
    };
    query?: never;
    url: '/admin/documents/{document_id}';
};

export type DeleteDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDocumentError = DeleteDocumentErrors[keyof DeleteDocumentErrors];

export type DeleteDocumentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateDocumentData = {
    body: DocumentCreate;
    path: {
        /**
         * Document Id
         */
        document_id: number;
    };
    query?: never;
    url: '/admin/documents/{document_id}';
};

export type UpdateDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDocumentError = UpdateDocumentErrors[keyof UpdateDocumentErrors];

export type UpdateDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentAdmin;
};

export type UpdateDocumentResponse = UpdateDocumentResponses[keyof UpdateDocumentResponses];

export type CreateLanguageData = {
    body: Language;
    path?: never;
    query?: never;
    url: '/admin/languages/';
};

export type CreateLanguageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLanguageError = CreateLanguageErrors[keyof CreateLanguageErrors];

export type CreateLanguageResponses = {
    /**
     * Successful Response
     */
    200: Language;
};

export type CreateLanguageResponse = CreateLanguageResponses[keyof CreateLanguageResponses];

export type DeleteLanguageData = {
    body?: never;
    path: {
        /**
         * Language Id
         */
        language_id: string;
    };
    query?: never;
    url: '/admin/languages/{language_id}';
};

export type DeleteLanguageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLanguageError = DeleteLanguageErrors[keyof DeleteLanguageErrors];

export type DeleteLanguageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateI18nData = {
    /**
     * I18Dict
     */
    body: {
        [key: string]: {
            [key: string]: string;
        };
    };
    path: {
        /**
         * Language Id
         */
        language_id: string;
    };
    query?: never;
    url: '/admin/i18n/{language_id}';
};

export type UpdateI18nErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateI18nError = UpdateI18nErrors[keyof UpdateI18nErrors];

export type UpdateI18nResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TranslateData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Text
         */
        text: string;
        /**
         * Locale
         */
        locale: string;
        /**
         * Source Lang
         */
        source_lang?: string;
    };
    url: '/admin/translate/';
};

export type TranslateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TranslateError = TranslateErrors[keyof TranslateErrors];

export type TranslateResponses = {
    /**
     * Response Translate
     *
     * Successful Response
     */
    200: string;
};

export type TranslateResponse = TranslateResponses[keyof TranslateResponses];

export type GetMilestoneGroupsAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/milestone-groups/';
};

export type GetMilestoneGroupsAdminResponses = {
    /**
     * Response Get Milestone Groups Admin
     *
     * Successful Response
     */
    200: Array<MilestoneGroupAdmin>;
};

export type GetMilestoneGroupsAdminResponse = GetMilestoneGroupsAdminResponses[keyof GetMilestoneGroupsAdminResponses];

export type CreateMilestoneGroupAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/milestone-groups/';
};

export type CreateMilestoneGroupAdminResponses = {
    /**
     * Successful Response
     */
    200: MilestoneGroupAdmin;
};

export type CreateMilestoneGroupAdminResponse = CreateMilestoneGroupAdminResponses[keyof CreateMilestoneGroupAdminResponses];

export type UpdateMilestoneGroupAdminData = {
    body: MilestoneGroupAdmin;
    path?: never;
    query?: never;
    url: '/admin/milestone-groups';
};

export type UpdateMilestoneGroupAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMilestoneGroupAdminError = UpdateMilestoneGroupAdminErrors[keyof UpdateMilestoneGroupAdminErrors];

export type UpdateMilestoneGroupAdminResponses = {
    /**
     * Successful Response
     */
    200: MilestoneGroupAdmin;
};

export type UpdateMilestoneGroupAdminResponse = UpdateMilestoneGroupAdminResponses[keyof UpdateMilestoneGroupAdminResponses];

export type DeleteMilestoneGroupAdminData = {
    body?: never;
    path: {
        /**
         * Milestone Group Id
         */
        milestone_group_id: number;
    };
    query?: {
        /**
         * Dry Run
         *
         * When true, shows what would be deleted without actually deleting
         */
        dry_run?: boolean;
    };
    url: '/admin/milestone-groups/{milestone_group_id}';
};

export type DeleteMilestoneGroupAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMilestoneGroupAdminError = DeleteMilestoneGroupAdminErrors[keyof DeleteMilestoneGroupAdminErrors];

export type DeleteMilestoneGroupAdminResponses = {
    /**
     * Successful Response
     */
    200: DeleteResponse;
};

export type DeleteMilestoneGroupAdminResponse = DeleteMilestoneGroupAdminResponses[keyof DeleteMilestoneGroupAdminResponses];

export type OrderMilestoneGroupsAdminData = {
    /**
     * Item Orders
     */
    body: Array<ItemOrder>;
    path?: never;
    query?: never;
    url: '/admin/milestone-groups/order/';
};

export type OrderMilestoneGroupsAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrderMilestoneGroupsAdminError = OrderMilestoneGroupsAdminErrors[keyof OrderMilestoneGroupsAdminErrors];

export type OrderMilestoneGroupsAdminResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadMilestoneGroupImageData = {
    body: BodyUploadMilestoneGroupImage;
    path: {
        /**
         * Milestone Group Id
         */
        milestone_group_id: number;
    };
    query?: never;
    url: '/admin/milestone-group-images/{milestone_group_id}';
};

export type UploadMilestoneGroupImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadMilestoneGroupImageError = UploadMilestoneGroupImageErrors[keyof UploadMilestoneGroupImageErrors];

export type UploadMilestoneGroupImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateMilestoneData = {
    body?: never;
    path: {
        /**
         * Milestone Group Id
         */
        milestone_group_id: number;
    };
    query?: never;
    url: '/admin/milestones/{milestone_group_id}';
};

export type CreateMilestoneErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMilestoneError = CreateMilestoneErrors[keyof CreateMilestoneErrors];

export type CreateMilestoneResponses = {
    /**
     * Successful Response
     */
    200: MilestoneAdmin;
};

export type CreateMilestoneResponse = CreateMilestoneResponses[keyof CreateMilestoneResponses];

export type UpdateMilestoneData = {
    body: MilestoneAdmin;
    path?: never;
    query?: never;
    url: '/admin/milestones/';
};

export type UpdateMilestoneErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMilestoneError = UpdateMilestoneErrors[keyof UpdateMilestoneErrors];

export type UpdateMilestoneResponses = {
    /**
     * Successful Response
     */
    200: MilestoneAdmin;
};

export type UpdateMilestoneResponse = UpdateMilestoneResponses[keyof UpdateMilestoneResponses];

export type DeleteMilestoneData = {
    body?: never;
    path: {
        /**
         * Milestone Id
         */
        milestone_id: number;
    };
    query?: {
        /**
         * Dry Run
         *
         * When true, shows what would be deleted without actually deleting
         */
        dry_run?: boolean;
    };
    url: '/admin/milestones/{milestone_id}';
};

export type DeleteMilestoneErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMilestoneError = DeleteMilestoneErrors[keyof DeleteMilestoneErrors];

export type DeleteMilestoneResponses = {
    /**
     * Successful Response
     */
    200: DeleteResponse;
};

export type DeleteMilestoneResponse = DeleteMilestoneResponses[keyof DeleteMilestoneResponses];

export type OrderMilestonesAdminData = {
    /**
     * Item Orders
     */
    body: Array<ItemOrder>;
    path?: never;
    query?: never;
    url: '/admin/milestones/order/';
};

export type OrderMilestonesAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrderMilestonesAdminError = OrderMilestonesAdminErrors[keyof OrderMilestonesAdminErrors];

export type OrderMilestonesAdminResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadMilestoneImageData = {
    body: BodyUploadMilestoneImage;
    path: {
        /**
         * Milestone Id
         */
        milestone_id: number;
    };
    query?: never;
    url: '/admin/milestone-images/{milestone_id}';
};

export type UploadMilestoneImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadMilestoneImageError = UploadMilestoneImageErrors[keyof UploadMilestoneImageErrors];

export type UploadMilestoneImageResponses = {
    /**
     * Successful Response
     */
    200: MilestoneImage;
};

export type UploadMilestoneImageResponse = UploadMilestoneImageResponses[keyof UploadMilestoneImageResponses];

export type DeleteMilestoneImageData = {
    body?: never;
    path: {
        /**
         * Milestone Image Id
         */
        milestone_image_id: number;
    };
    query?: never;
    url: '/admin/milestone-images/{milestone_image_id}';
};

export type DeleteMilestoneImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMilestoneImageError = DeleteMilestoneImageErrors[keyof DeleteMilestoneImageErrors];

export type DeleteMilestoneImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSubmittedMilestoneImagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/submitted-milestone-images/';
};

export type GetSubmittedMilestoneImagesResponses = {
    /**
     * Response Get Submitted Milestone Images
     *
     * Successful Response
     */
    200: Array<SubmittedMilestoneImagePublic>;
};

export type GetSubmittedMilestoneImagesResponse = GetSubmittedMilestoneImagesResponses[keyof GetSubmittedMilestoneImagesResponses];

export type ApproveSubmittedMilestoneImageData = {
    body?: never;
    path: {
        /**
         * Submitted Milestone Image Id
         */
        submitted_milestone_image_id: number;
    };
    query?: never;
    url: '/admin/submitted-milestone-images/approve/{submitted_milestone_image_id}';
};

export type ApproveSubmittedMilestoneImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveSubmittedMilestoneImageError = ApproveSubmittedMilestoneImageErrors[keyof ApproveSubmittedMilestoneImageErrors];

export type ApproveSubmittedMilestoneImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteSubmittedMilestoneImageData = {
    body?: never;
    path: {
        /**
         * Submitted Milestone Image Id
         */
        submitted_milestone_image_id: number;
    };
    query?: never;
    url: '/admin/submitted-milestone-images/{submitted_milestone_image_id}';
};

export type DeleteSubmittedMilestoneImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSubmittedMilestoneImageError = DeleteSubmittedMilestoneImageErrors[keyof DeleteSubmittedMilestoneImageErrors];

export type DeleteSubmittedMilestoneImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMilestoneAgeScoresData = {
    body?: never;
    path: {
        /**
         * Milestone Id
         */
        milestone_id: number;
    };
    query?: never;
    url: '/admin/milestone-age-scores/{milestone_id}';
};

export type GetMilestoneAgeScoresErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMilestoneAgeScoresError = GetMilestoneAgeScoresErrors[keyof GetMilestoneAgeScoresErrors];

export type GetMilestoneAgeScoresResponses = {
    /**
     * Successful Response
     */
    200: MilestoneAgeScoreCollectionPublic;
};

export type GetMilestoneAgeScoresResponse = GetMilestoneAgeScoresResponses[keyof GetMilestoneAgeScoresResponses];

export type AdminUpdateStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/update-stats/';
};

export type AdminUpdateStatsResponses = {
    /**
     * Successful Response
     */
    200: StatisticsUpdateResult;
};

export type AdminUpdateStatsResponse = AdminUpdateStatsResponses[keyof AdminUpdateStatsResponses];

export type GetMilestoneAnswerSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/milestone-answer-sessions/';
};

export type GetMilestoneAnswerSessionsResponses = {
    /**
     * Response Get Milestone Answer Sessions
     *
     * Successful Response
     */
    200: Array<MilestoneAnswerSession>;
};

export type GetMilestoneAnswerSessionsResponse = GetMilestoneAnswerSessionsResponses[keyof GetMilestoneAnswerSessionsResponses];

export type ModifyMilestoneAnswerSessionData = {
    body?: never;
    path: {
        /**
         * Answer Session Id
         */
        answer_session_id: number;
    };
    query: {
        /**
         * Suspicious
         */
        suspicious: boolean;
    };
    url: '/admin/milestone-answer-sessions/{answer_session_id}';
};

export type ModifyMilestoneAnswerSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ModifyMilestoneAnswerSessionError = ModifyMilestoneAnswerSessionErrors[keyof ModifyMilestoneAnswerSessionErrors];

export type ModifyMilestoneAnswerSessionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMilestoneAnswerSessionAnalysisData = {
    body?: never;
    path: {
        /**
         * Answer Session Id
         */
        answer_session_id: number;
    };
    query?: never;
    url: '/admin/milestone-answer-session-analysis/{answer_session_id}';
};

export type GetMilestoneAnswerSessionAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMilestoneAnswerSessionAnalysisError = GetMilestoneAnswerSessionAnalysisErrors[keyof GetMilestoneAnswerSessionAnalysisErrors];

export type GetMilestoneAnswerSessionAnalysisResponses = {
    /**
     * Successful Response
     */
    200: MilestoneAnswerSessionAnalysis;
};

export type GetMilestoneAnswerSessionAnalysisResponse = GetMilestoneAnswerSessionAnalysisResponses[keyof GetMilestoneAnswerSessionAnalysisResponses];

export type GetUserQuestionsAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/user-questions/';
};

export type GetUserQuestionsAdminResponses = {
    /**
     * Response Get User Questions Admin
     *
     * Successful Response
     */
    200: Array<UserQuestionAdmin>;
};

export type GetUserQuestionsAdminResponse = GetUserQuestionsAdminResponses[keyof GetUserQuestionsAdminResponses];

export type CreateUserQuestionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/user-questions/';
};

export type CreateUserQuestionResponses = {
    /**
     * Successful Response
     */
    200: UserQuestionAdmin;
};

export type CreateUserQuestionResponse = CreateUserQuestionResponses[keyof CreateUserQuestionResponses];

export type UpdateUserQuestionData = {
    body: UserQuestionAdmin;
    path?: never;
    query?: never;
    url: '/admin/user-questions/';
};

export type UpdateUserQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserQuestionError = UpdateUserQuestionErrors[keyof UpdateUserQuestionErrors];

export type UpdateUserQuestionResponses = {
    /**
     * Successful Response
     */
    200: UserQuestionAdmin;
};

export type UpdateUserQuestionResponse = UpdateUserQuestionResponses[keyof UpdateUserQuestionResponses];

export type DeleteUserQuestionData = {
    body?: never;
    path: {
        /**
         * User Question Id
         */
        user_question_id: number;
    };
    query?: {
        /**
         * Dry Run
         *
         * When true, shows what would be deleted without actually deleting
         */
        dry_run?: boolean;
    };
    url: '/admin/user-questions/{user_question_id}';
};

export type DeleteUserQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserQuestionError = DeleteUserQuestionErrors[keyof DeleteUserQuestionErrors];

export type DeleteUserQuestionResponses = {
    /**
     * Successful Response
     */
    200: DeleteResponse;
};

export type DeleteUserQuestionResponse = DeleteUserQuestionResponses[keyof DeleteUserQuestionResponses];

export type OrderUserQuestionsAdminData = {
    /**
     * Item Orders
     */
    body: Array<ItemOrder>;
    path?: never;
    query?: never;
    url: '/admin/user-questions/order/';
};

export type OrderUserQuestionsAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrderUserQuestionsAdminError = OrderUserQuestionsAdminErrors[keyof OrderUserQuestionsAdminErrors];

export type OrderUserQuestionsAdminResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetChildQuestionsAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/child-questions/';
};

export type GetChildQuestionsAdminResponses = {
    /**
     * Response Get Child Questions Admin
     *
     * Successful Response
     */
    200: Array<ChildQuestionAdmin>;
};

export type GetChildQuestionsAdminResponse = GetChildQuestionsAdminResponses[keyof GetChildQuestionsAdminResponses];

export type CreateChildQuestionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/child-questions/';
};

export type CreateChildQuestionResponses = {
    /**
     * Successful Response
     */
    200: ChildQuestionAdmin;
};

export type CreateChildQuestionResponse = CreateChildQuestionResponses[keyof CreateChildQuestionResponses];

export type UpdateChildQuestionData = {
    body: ChildQuestionAdmin;
    path?: never;
    query?: never;
    url: '/admin/child-questions/';
};

export type UpdateChildQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateChildQuestionError = UpdateChildQuestionErrors[keyof UpdateChildQuestionErrors];

export type UpdateChildQuestionResponses = {
    /**
     * Successful Response
     */
    200: ChildQuestionAdmin;
};

export type UpdateChildQuestionResponse = UpdateChildQuestionResponses[keyof UpdateChildQuestionResponses];

export type DeleteChildQuestionData = {
    body?: never;
    path: {
        /**
         * Child Question Id
         */
        child_question_id: number;
    };
    query?: {
        /**
         * Dry Run
         *
         * When true, shows what would be deleted without actually deleting
         */
        dry_run?: boolean;
    };
    url: '/admin/child-questions/{child_question_id}';
};

export type DeleteChildQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteChildQuestionError = DeleteChildQuestionErrors[keyof DeleteChildQuestionErrors];

export type DeleteChildQuestionResponses = {
    /**
     * Successful Response
     */
    200: DeleteResponse;
};

export type DeleteChildQuestionResponse = DeleteChildQuestionResponses[keyof DeleteChildQuestionResponses];

export type OrderChildQuestionsAdminData = {
    /**
     * Item Orders
     */
    body: Array<ItemOrder>;
    path?: never;
    query?: never;
    url: '/admin/child-questions/order/';
};

export type OrderChildQuestionsAdminErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrderChildQuestionsAdminError = OrderChildQuestionsAdminErrors[keyof OrderChildQuestionsAdminErrors];

export type OrderChildQuestionsAdminResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAdminSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/settings/';
};

export type GetAdminSettingsResponses = {
    /**
     * Successful Response
     */
    200: AdminSettingsPublic;
};

export type GetAdminSettingsResponse = GetAdminSettingsResponses[keyof GetAdminSettingsResponses];

export type UpdateAdminSettingsData = {
    body: AdminSettingsUpdate;
    path?: never;
    query?: never;
    url: '/admin/settings/';
};

export type UpdateAdminSettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAdminSettingsError = UpdateAdminSettingsErrors[keyof UpdateAdminSettingsErrors];

export type UpdateAdminSettingsResponses = {
    /**
     * Successful Response
     */
    200: AdminSettingsPublic;
};

export type UpdateAdminSettingsResponse = UpdateAdminSettingsResponses[keyof UpdateAdminSettingsResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/users/';
};

export type GetUsersResponses = {
    /**
     * Response Get Users
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetResearchGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/research-groups/';
};

export type GetResearchGroupsResponses = {
    /**
     * Response Get Research Groups
     *
     * Successful Response
     */
    200: Array<ResearchGroup>;
};

export type GetResearchGroupsResponse = GetResearchGroupsResponses[keyof GetResearchGroupsResponses];

export type CreateResearchGroupData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/admin/research-groups/{user_id}';
};

export type CreateResearchGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateResearchGroupError = CreateResearchGroupErrors[keyof CreateResearchGroupErrors];

export type CreateResearchGroupResponses = {
    /**
     * Successful Response
     */
    200: ResearchGroup;
};

export type CreateResearchGroupResponse = CreateResearchGroupResponses[keyof CreateResearchGroupResponses];

export type DeleteResearchGroupData = {
    body?: never;
    path: {
        /**
         * Research Group Id
         */
        research_group_id: number;
    };
    query?: never;
    url: '/admin/research-groups/{research_group_id}';
};

export type DeleteResearchGroupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteResearchGroupError = DeleteResearchGroupErrors[keyof DeleteResearchGroupErrors];

export type DeleteResearchGroupResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ImportCsvDataData = {
    body: BodyImportCsvData;
    path?: never;
    query?: never;
    url: '/admin/research/import-csv/';
};

export type ImportCsvDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportCsvDataError = ImportCsvDataErrors[keyof ImportCsvDataErrors];

export type ImportCsvDataResponses = {
    /**
     * Successful Response
     */
    200: ImportCsvResponse;
};

export type ImportCsvDataResponse = ImportCsvDataResponses[keyof ImportCsvDataResponses];

export type UsersCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersCurrentUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type UsersCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersCurrentUserResponse = UsersCurrentUserResponses[keyof UsersCurrentUserResponses];

export type UsersPatchCurrentUserData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersPatchCurrentUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchCurrentUserError = UsersPatchCurrentUserErrors[keyof UsersPatchCurrentUserErrors];

export type UsersPatchCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchCurrentUserResponse = UsersPatchCurrentUserResponses[keyof UsersPatchCurrentUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUserError = UsersUserErrors[keyof UsersUserErrors];

export type UsersUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUserResponse = UsersUserResponses[keyof UsersUserResponses];

export type UsersPatchUserData = {
    body: UserUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersPatchUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchUserError = UsersPatchUserErrors[keyof UsersPatchUserErrors];

export type UsersPatchUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchUserResponse = UsersPatchUserResponses[keyof UsersPatchUserResponses];

export type GetChildrenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/children/';
};

export type GetChildrenResponses = {
    /**
     * Response Get Children
     *
     * Successful Response
     */
    200: Array<ChildSummaryPublic>;
};

export type GetChildrenResponse = GetChildrenResponses[keyof GetChildrenResponses];

export type CreateChildData = {
    body: ChildCreate;
    path?: never;
    query?: never;
    url: '/users/children/';
};

export type CreateChildErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChildError = CreateChildErrors[keyof CreateChildErrors];

export type CreateChildResponses = {
    /**
     * Successful Response
     */
    200: ChildPublic;
};

export type CreateChildResponse = CreateChildResponses[keyof CreateChildResponses];

export type UpdateChildData = {
    body: ChildPublic;
    path?: never;
    query?: never;
    url: '/users/children/';
};

export type UpdateChildErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateChildError = UpdateChildErrors[keyof UpdateChildErrors];

export type UpdateChildResponses = {
    /**
     * Successful Response
     */
    200: ChildPublic;
};

export type UpdateChildResponse = UpdateChildResponses[keyof UpdateChildResponses];

export type DeleteChildData = {
    body?: never;
    path: {
        /**
         * Child Id
         */
        child_id: number;
    };
    query?: {
        /**
         * Dry Run
         *
         * When true, shows what would be deleted without actually deleting
         */
        dry_run?: boolean;
    };
    url: '/users/children/{child_id}';
};

export type DeleteChildErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteChildError = DeleteChildErrors[keyof DeleteChildErrors];

export type DeleteChildResponses = {
    /**
     * Successful Response
     */
    200: DeleteResponse;
};

export type DeleteChildResponse = DeleteChildResponses[keyof DeleteChildResponses];

export type GetChildData = {
    body?: never;
    path: {
        /**
         * Child Id
         */
        child_id: number;
    };
    query?: never;
    url: '/users/children/{child_id}';
};

export type GetChildErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChildError = GetChildErrors[keyof GetChildErrors];

export type GetChildResponses = {
    /**
     * Successful Response
     */
    200: ChildPublic;
};

export type GetChildResponse = GetChildResponses[keyof GetChildResponses];

export type DeleteChildImageData = {
    body?: never;
    path: {
        /**
         * Child Id
         */
        child_id: number;
    };
    query?: never;
    url: '/users/children-images/{child_id}';
};

export type DeleteChildImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteChildImageError = DeleteChildImageErrors[keyof DeleteChildImageErrors];

export type DeleteChildImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetChildImageData = {
    body?: never;
    path: {
        /**
         * Child Id
         */
        child_id: number;
    };
    query?: never;
    url: '/users/children-images/{child_id}';
};

export type GetChildImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChildImageError = GetChildImageErrors[keyof GetChildImageErrors];

export type GetChildImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadChildImageData = {
    body: BodyUploadChildImage;
    path: {
        /**
         * Child Id
         */
        child_id: number;
    };
    query?: never;
    url: '/users/children-images/{child_id}';
};

export type UploadChildImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadChildImageError = UploadChildImageErrors[keyof UploadChildImageErrors];

export type UploadChildImageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentMilestoneAnswerSessionData = {
    body?: never;
    path: {
        /**
         * Child Id
         */
        child_id: number;
    };
    query?: never;
    url: '/users/milestone-answers/{child_id}';
};

export type GetCurrentMilestoneAnswerSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCurrentMilestoneAnswerSessionError = GetCurrentMilestoneAnswerSessionErrors[keyof GetCurrentMilestoneAnswerSessionErrors];

export type GetCurrentMilestoneAnswerSessionResponses = {
    /**
     * Successful Response
     */
    200: MilestoneAnswerSessionPublic;
};

export type GetCurrentMilestoneAnswerSessionResponse = GetCurrentMilestoneAnswerSessionResponses[keyof GetCurrentMilestoneAnswerSessionResponses];

export type UpdateMilestoneAnswerData = {
    body: MilestoneAnswerPublic;
    path: {
        /**
         * Milestone Answer Session Id
         */
        milestone_answer_session_id: number;
    };
    query?: never;
    url: '/users/milestone-answers/{milestone_answer_session_id}';
};

export type UpdateMilestoneAnswerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMilestoneAnswerError = UpdateMilestoneAnswerErrors[keyof UpdateMilestoneAnswerErrors];

export type UpdateMilestoneAnswerResponses = {
    /**
     * Successful Response
     */
    200: MilestoneAnswerResponse;
};

export type UpdateMilestoneAnswerResponse = UpdateMilestoneAnswerResponses[keyof UpdateMilestoneAnswerResponses];

export type GetCurrentUserAnswersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/user-answers/';
};

export type GetCurrentUserAnswersResponses = {
    /**
     * Response Get Current User Answers
     *
     * Successful Response
     */
    200: Array<UserAnswerPublic>;
};

export type GetCurrentUserAnswersResponse = GetCurrentUserAnswersResponses[keyof GetCurrentUserAnswersResponses];

export type UpdateCurrentUserAnswersData = {
    /**
     * New Answers
     */
    body: Array<UserAnswerPublic>;
    path?: never;
    query?: never;
    url: '/users/user-answers/';
};

export type UpdateCurrentUserAnswersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentUserAnswersError = UpdateCurrentUserAnswersErrors[keyof UpdateCurrentUserAnswersErrors];

export type UpdateCurrentUserAnswersResponses = {
    /**
     * Response Update Current User Answers
     *
     * Successful Response
     */
    200: Array<UserAnswerPublic>;
};

export type UpdateCurrentUserAnswersResponse = UpdateCurrentUserAnswersResponses[keyof UpdateCurrentUserAnswersResponses];

export type GetCurrentChildAnswersData = {
    body?: never;
    path: {
        /**
         * Child Id
         */
        child_id: number;
    };
    query?: never;
    url: '/users/children-answers/{child_id}';
};

export type GetCurrentChildAnswersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCurrentChildAnswersError = GetCurrentChildAnswersErrors[keyof GetCurrentChildAnswersErrors];

export type GetCurrentChildAnswersResponses = {
    /**
     * Response Get Current Child Answers
     *
     * Successful Response
     */
    200: {
        [key: string]: ChildAnswerPublic;
    };
};

export type GetCurrentChildAnswersResponse = GetCurrentChildAnswersResponses[keyof GetCurrentChildAnswersResponses];

export type UpdateCurrentChildAnswersData = {
    /**
     * New Answers
     */
    body: {
        [key: string]: ChildAnswerPublic;
    };
    path: {
        /**
         * Child Id
         */
        child_id: number;
    };
    query?: never;
    url: '/users/children-answers/{child_id}';
};

export type UpdateCurrentChildAnswersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentChildAnswersError = UpdateCurrentChildAnswersErrors[keyof UpdateCurrentChildAnswersErrors];

export type UpdateCurrentChildAnswersResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCompletedMilestoneAnswerSessionsData = {
    body?: never;
    path: {
        /**
         * Child Id
         */
        child_id: number;
    };
    query?: never;
    url: '/users/milestone-answers-sessions/{child_id}';
};

export type GetCompletedMilestoneAnswerSessionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCompletedMilestoneAnswerSessionsError = GetCompletedMilestoneAnswerSessionsErrors[keyof GetCompletedMilestoneAnswerSessionsErrors];

export type GetCompletedMilestoneAnswerSessionsResponses = {
    /**
     * Response Get Completed Milestone Answer Sessions
     *
     * Successful Response
     */
    200: {
        [key: string]: MilestoneAnswerSessionPublic;
    };
};

export type GetCompletedMilestoneAnswerSessionsResponse = GetCompletedMilestoneAnswerSessionsResponses[keyof GetCompletedMilestoneAnswerSessionsResponses];

export type GetMilestonegroupsForSessionData = {
    body?: never;
    path: {
        /**
         * Answersession Id
         */
        answersession_id: number;
    };
    query?: never;
    url: '/users/feedback/answersession={answersession_id}';
};

export type GetMilestonegroupsForSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMilestonegroupsForSessionError = GetMilestonegroupsForSessionErrors[keyof GetMilestonegroupsForSessionErrors];

export type GetMilestonegroupsForSessionResponses = {
    /**
     * Response Get Milestonegroups For Session
     *
     * Successful Response
     */
    200: {
        [key: string]: MilestoneGroupPublic;
    };
};

export type GetMilestonegroupsForSessionResponse = GetMilestonegroupsForSessionResponses[keyof GetMilestonegroupsForSessionResponses];

export type GetSummaryFeedbackForAnswersessionData = {
    body?: never;
    path: {
        /**
         * Answersession Id
         */
        answersession_id: number;
    };
    query?: never;
    url: '/users/feedback/answersession={answersession_id}/summary';
};

export type GetSummaryFeedbackForAnswersessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSummaryFeedbackForAnswersessionError = GetSummaryFeedbackForAnswersessionErrors[keyof GetSummaryFeedbackForAnswersessionErrors];

export type GetSummaryFeedbackForAnswersessionResponses = {
    /**
     * Response Get Summary Feedback For Answersession
     *
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type GetSummaryFeedbackForAnswersessionResponse = GetSummaryFeedbackForAnswersessionResponses[keyof GetSummaryFeedbackForAnswersessionResponses];

export type GetDetailedFeedbackForAnswersessionData = {
    body?: never;
    path: {
        /**
         * Answersession Id
         */
        answersession_id: number;
    };
    query?: never;
    url: '/users/feedback/answersession={answersession_id}/detailed';
};

export type GetDetailedFeedbackForAnswersessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDetailedFeedbackForAnswersessionError = GetDetailedFeedbackForAnswersessionErrors[keyof GetDetailedFeedbackForAnswersessionErrors];

export type GetDetailedFeedbackForAnswersessionResponses = {
    /**
     * Response Get Detailed Feedback For Answersession
     *
     * Successful Response
     */
    200: {
        [key: string]: {
            [key: string]: number;
        };
    };
};

export type GetDetailedFeedbackForAnswersessionResponse = GetDetailedFeedbackForAnswersessionResponses[keyof GetDetailedFeedbackForAnswersessionResponses];

export type AuthCookieLoginData = {
    body: Login;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthCookieLoginErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthCookieLoginError = AuthCookieLoginErrors[keyof AuthCookieLoginErrors];

export type AuthCookieLoginResponses = {
    /**
     * Successful Response
     */
    200: unknown;
    /**
     * No Content
     */
    204: void;
};

export type AuthCookieLoginResponse = AuthCookieLoginResponses[keyof AuthCookieLoginResponses];

export type AuthCookieLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthCookieLogoutErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type AuthCookieLogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
    /**
     * No Content
     */
    204: void;
};

export type AuthCookieLogoutResponse = AuthCookieLogoutResponses[keyof AuthCookieLogoutResponses];

export type RegisterRegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterRegisterErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterRegisterError = RegisterRegisterErrors[keyof RegisterRegisterErrors];

export type RegisterRegisterResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterRegisterResponse = RegisterRegisterResponses[keyof RegisterRegisterResponses];

export type ResetForgotPasswordData = {
    body: BodyResetForgotPassword;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type ResetForgotPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetForgotPasswordError = ResetForgotPasswordErrors[keyof ResetForgotPasswordErrors];

export type ResetForgotPasswordResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ResetResetPasswordData = {
    body: BodyResetResetPassword;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetResetPasswordError = ResetResetPasswordErrors[keyof ResetResetPasswordErrors];

export type ResetResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyRequestTokenData = {
    body: BodyVerifyRequestToken;
    path?: never;
    query?: never;
    url: '/auth/request-verify-token';
};

export type VerifyRequestTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyRequestTokenError = VerifyRequestTokenErrors[keyof VerifyRequestTokenErrors];

export type VerifyRequestTokenResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type VerifyVerifyData = {
    body: BodyVerifyVerify;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type VerifyVerifyErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyVerifyError = VerifyVerifyErrors[keyof VerifyVerifyErrors];

export type VerifyVerifyResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type VerifyVerifyResponse = VerifyVerifyResponses[keyof VerifyVerifyResponses];

export type ReauthenticateSessionData = {
    body: SessionReauthentication;
    path?: never;
    query?: never;
    url: '/auth/session/reauthenticate';
};

export type ReauthenticateSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReauthenticateSessionError = ReauthenticateSessionErrors[keyof ReauthenticateSessionErrors];

export type ReauthenticateSessionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ReauthenticateSessionResponse = ReauthenticateSessionResponses[keyof ReauthenticateSessionResponses];

export type GetResearchDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/research/data/';
};

export type GetResearchDataResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetResearchNamesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/research/names/';
};

export type GetResearchNamesResponses = {
    /**
     * Response Get Research Names
     *
     * Successful Response
     */
    200: {
        [key: string]: {
            [key: string]: string;
        };
    };
};

export type GetResearchNamesResponse = GetResearchNamesResponses[keyof GetResearchNamesResponses];
