name: run tests 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps: 
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm run test