name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm build
      - run: pnpm run test:unit
      - uses: codecov/codecov-action@v5
        with:
          files: ./frontend/coverage/coverage-final.json
          name: frontend
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
  backend-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mondey_backend
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -e .[tests]
      - run: python -m pytest --cov=mondey_backend --cov-report=xml -svvv
      - uses: codecov/codecov-action@v5
        with:
          files: ./mondey_backend/coverage.xml
          name: backend
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
  logged-in-ui-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      # Setup Python for backend
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install backend dependencies
        working-directory: ./mondey_backend
        run: pip install -e .

      # Setup Node.js and pnpm for frontend
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      # Install frontend dependencies and build
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: pnpm install
      - name: Build frontend
        working-directory: ./frontend
        run: pnpm build
      - name: Install Playwright
        working-directory: ./frontend
        run: pnpm exec playwright install --with-deps

      # Start backend server
      - name: Start backend server
        working-directory: ./mondey_backend
        run: mondey-backend &

      # Wait for backend to start
      - name: Wait for backend to be ready
        run: |
          timeout=30
          while ! curl -s http://localhost:8000 2>&1 > /dev/null
          do
            if [ $timeout -le 0 ]; then
              echo "Backend failed to start"
              exit 1
            fi
            echo "Waiting for backend to be ready... ($timeout seconds left)"
            timeout=$((timeout-1))
            sleep 1
          done
          echo "Backend is ready!"

      # Run the logged-in UI tests
      - name: Run logged-in UI tests
        working-directory: ./frontend
        run: pnpm test:ui

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7
