name: run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm build
      - run: pnpm run test
      - uses: codecov/codecov-action@v5
        with:
          files: ./frontend/coverage/coverage-final.json
          name: frontend
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
  backend-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mondey_backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -e .[tests]
      - run: python -m pytest --cov=mondey_backend --cov-report=xml -svvv
      - uses: codecov/codecov-action@v5
        with:
          files: ./mondey_backend/coverage.xml
          name: backend
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
