name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm build
      - run: pnpm run test:unit || exit 1
      - uses: codecov/codecov-action@v5
        with:
          files: ./frontend/coverage/coverage-final.json
          name: frontend
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
  backend-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mondey_backend
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -e .[tests]
      - run: python -m pytest --cov=mondey_backend --cov-report=xml -svvv
      - uses: codecov/codecov-action@v5
        with:
          files: ./mondey_backend/coverage.xml
          name: backend
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
  frontend-ui-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm exec playwright install --with-deps
      - run: pnpm build
      - run: pnpm run test:ui || exit 1
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: frontend-ui-tests-playwright-report
          path: frontend/playwright-report/
          retention-days: 7
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      # Setup Python for backend
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install backend
        working-directory: ./mondey_backend
        run: pip install -e .

      # Start backend server
      - name: Start backend server in directory with e2e test database and SQL.
        working-directory: ./e2e
        run: |
          mkdir -p logs
          RELOAD=false SMTP_HOST="" E2E_TEST_SQL_FILES="db/importBaseMetadata.sql;db/importMilestoneAnswers.sql" mondey-backend

      # Setup Node.js and pnpm for frontend
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: pnpm install
      - name: Build frontend
        working-directory: ./frontend
        run: pnpm build
      - name: Install Playwright
        working-directory: ./frontend
        run: pnpm exec playwright install --with-deps

      # Print current time before running e2e tests
      - name: Print current time before e2e tests
        run: echo "Current time before running e2e tests is $(date)"

      # Run the e2e tests
      - name: Run e2e tests
        working-directory: ./frontend
        run: pnpm test:e2e || exit 1

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: e2e-tests-playwright-report
          path: frontend/playwright-report/
          retention-days: 7

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: backend-e2e-logs
          path: ./e2e/logs/
          retention-days: 7
